### ISSUE TITLE
_hashQuads uses SHA-1, not SHA-256

### ISSUE THREAD

**Issue by gkellogg** [digitalbazaar/jsonld.js#100]
The Dataset Normalization spec specifies "The hash algorithm used by URDNA2015, namely, SHA-256", `_hashQuads` uses SHA-1, resulting in output discrepancies with expected JSON-LD normalization test results.

**Comment by dlongley** [comment]
To be clear, we need to continue to support URGNA2011, which used SHA-1 and also support the newer URDNA2015, which uses SHA-256.

**Comment by gkellogg** [comment]
Sure, are there other differences? I presume the existing tests in the json-ld.org suite are URDNA2012 then. Is there a suite for 2015?

**Comment by dlongley** [comment]
Yes, there are other differences. They are minor to implement, but likely affect the outcome to the point that an entirely different test suite is necessary for URDNA2015. And, no, we don't have that separate test suite yet.

I haven't yet had the time to split out the differences in the existing implementations (js, python, php... all of which implement URGNA2012 and are compliant with each other and the existing test suite) and what's in the URDNA2015 spec. Unfortunately, there's little hope of implementing URGNA2012 without that list of differences -- as there's no spec out there for it. There are only those mentioned interoperable implementations.

The URDNA2015 spec is based off of reading the URGNA2012 implementations and then adding some minor improvements to better support datasets, use a newer, larger hash with fewer potential collisions, and clean up some delimiter/padding issues. I need to update the existing implementations to support both URGNA2012 and URDNA2015 and generate a new test suite from it so we can compare those implementations with your own.

That work has all been on the backburner, but now that you're working on an implementation, I'll need to bring it up to speed. We need to update the test suite so it can take a normalization algorithm identifier (either `URGNA2012` or `URDNA2015`) to indicate which algorithm to run and which output to check against.

The quickest thing I can probably do at the moment is go back through the spec and add temporary issue markers where URDNA2015 has changed from URGNA2012.

**Comment by dlongley** [comment]
Closing as addressed/no longer relevant to this repo.
