### ISSUE TITLE
Add expandIri to the public API

### ISSUE THREAD

**Issue by bergos** [digitalbazaar/jsonld.js#103]
I'm using [this](https://github.com/bergos/hydra-core/blob/master/hydra-core.js#L28) ugly workaround to expand IRIs. It would be nice to reuse JSON-LD code in a simpler way.

**Comment by dlongley** [comment]
So what you want to do is expand a relative IRI, given a base?

ie: https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L5590

**Comment by dlongley** [comment]
That link should have been to `_prependBase`: https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L5498

**Comment by bergos** [comment]
Yes, _prependBase looks better
