### ISSUE TITLE
Undefined function error in _expandIri function

### ISSUE THREAD

**Issue by kevinprotoss** [digitalbazaar/jsonld.js#106]
Hi, 

I think I met across a bug in jsonld.js. You can see this error in the playground as well.

https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L5450

If I define a document like the following

```json
{
    "@context": {
        "customizable": {
          "@type": "@id",
          "@id": "http://www.xxx.com/test#customizable"
        }
    },
    "@id": "http://www.xxx.com/test",
    "customizable": false
}
```

Sure, the context is wrong, but I think jsonld should not throw an `Undefined function` exception.

Bg,
Kevin

**Comment by dlongley** [comment]
Yeah, looks like a bug. Will work on a patch when I can.
