### ISSUE TITLE
Compaction / Dereferencing

### ISSUE THREAD

**Issue by KevinMartin** [digitalbazaar/jsonld.js#111]
Hi,

I'm trying to figure out how to get an array of root-level objects to be compressed into one root object.

Original:
```json
[
  {
    "@id": "_:0",
    "@type": [
      "http://schema.org/Person"
    ],
    "http://schema.org/name": [
      {
        "@value": "John"
      }
    ],
    "http://schema.org/address": [
      {
        "@id": "_:1"
      }
    ]
  },
  {
    "@id": "_:1",
    "@type": "http://schema.org/PostalAddress",
    "http://schema.org/addressCountry": "USA"
  }
]
```

Expected Result:
```json
  {
    "@type": "http://schema.org/Person",
    "http://schema.org/name": "John",
    "http://schema.org/address": {
      "http://schema.org/addressCountry": "USA"
    }
  }
```

I'm currently doing:
```js
jsonld.compact(original, {}, ...);
```

Is this wrong?

**Comment by dlongley** [comment]
Compaction won't modify the shape of the data like that; you need to use Framing. Framing allows you to modify the shape of the data by "filtering/querying by example". You specify a "frame" that contains the `@type` or properties you're looking for as the root object. Every match in the data you apply the frame to will become a root object with any references embedded underneath it. You can get more fine-grained control over embedding by using the "@embed" keyword in your frame.

Documentation on some framing features is sparse at the moment, but you can play around with it on the JSON-LD playground:

See: http://json-ld.org/playground/#/gist/6a7bb32abc759dd672f1

```js
jsonld.frame(original, frame, ...);
```

**Comment by KevinMartin** [comment]
Perfect. I did it with the following:
```js
jsonld.frame(original, { '@type': original[0]['@type'] }, ...);
```
