### ISSUE TITLE
"@id" does not expand properly

### ISSUE THREAD

**Issue by ghost** [digitalbazaar/jsonld.js#114]
Consider the following snippet...

```
   MODEL = {
    "@context" : {
        "owl" : "http://www.w3.org/2002/07/owl#",
        "schema" : "http://schema.org/",
        "Class" : "owl:Class",
        "CreativeWork" : "schema:CreativeWork"
    },
    "@id" : "CreativeWork",
    "@type" : "Class",
};

jsonld.expand(MODEL, function(err, expanded){
    var text = JSON.stringify(expanded);
    // display text
});
```

The "@id" value should be expanded to "http://schema.org/CreativeWork", but it does not get expanded.  The "@id" value is unchanged by the expand operation.

**Comment by dlongley** [comment]
This is correct behavior per the spec, see [7.4.3 of the Expansion Algorithm](http://www.w3.org/TR/json-ld-api/#expansion-algorithm). The `vocab` flag is not set to `true` as it is for `@type` on 7.4.4.

The value of `@id` does not undergo vocabulary expansion as it is not considered part of any vocabulary. Rather the value of `@id` identifies a node in the graph. I know how this can be troublesome when marking up vocabulary items themselves (as it appears you're doing here), as I've bumped into it myself.
