### ISSUE TITLE
How to keep null value after compact

### ISSUE THREAD

**Issue by kevinprotoss** [digitalbazaar/jsonld.js#118]
Hi,

because of the persistence of JSON-LD, I must know which properties are required to be forget or clear by setting null for them. However, after compact function, all these infos are missing. Is there any mechanism or argument to prevent that. This means the null value won't be removed, at least the null values in the document, not context.

Bg,
Kevin

**Comment by dlongley** [comment]
JSON literals can be used for preserving null now.
