### ISSUE TITLE
Docs for setting up custom JSON-LD schema server + registry?

### ISSUE THREAD

**Issue by kevinSuttle** [digitalbazaar/jsonld.js#120]
Does such a doc set exist?

**Comment by davidlehn** [comment]
What is a "custom JSON-LD schema server + registry"?

**Comment by kevinSuttle** [comment]
If I wanted to create my own JSON-LD schema validation server, against a custom `@context`.

**Comment by dlongley** [comment]
We don't have such docs here -- and probably won't in the foreseeable future. Opening an issue at json-ld.org may be helpful as a community tooling thing.
