### ISSUE TITLE
N-Quads parser doesn't allow comments

### ISSUE THREAD

**Issue by jindrichmynarz** [digitalbazaar/jsonld.js#121]
The [N-Quads parser](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L6816-L6933) doesn't allow the parsed data to contain comments. As the [N-Quads specification](http://www.w3.org/TR/n-quads/#h2_sec-grammar) says: 

> Comments in N-Quads take the form of '#', outside an IRIREF or STRING_LITERAL_QUOTE, and continue to the end of line (EOL) or end of file if there is no end of line after the comment marker. Comments are treated as white space.

However, if I try to parse the following N-Quads (or any other N-Quads containing comments) using jsonld.js, it throws `jsonld.ParseError: Error while parsing N-Quads; invalid quad.`:

```
# NQuads
<http://example.com/resource/person/1> <http://xmlns.com/foaf/0.1/name> "Person 1" <http://example.com/resource/graph/1> .
```

Can the parser be extended to allow comments?

**Comment by dlongley** [comment]
> Can the parser be extended to allow comments?

Yes, but it's just a matter of having the time to do it. PRs are welcome.

**Comment by jindrichmynarz** [comment]
The fix seemed straightforward enough. A test is added in <https://github.com/json-ld/json-ld.org/pull/406>.

**Comment by jindrichmynarz** [comment]
I realized `$` in brackets is treated literally, therefore comment containing dollar signs won't be parsed. Shall I create a new pull request with <https://github.com/jindrichmynarz/jsonld.js/commit/7baa6df165ad7fe721bf3fbbe4c8265f58ab97d9>?

**Comment by dlongley** [comment]
@jindrichmynarz,

Yeah, both of those things sound good. Thanks!

**Comment by jindrichmynarz** [comment]
Done in <https://github.com/digitalbazaar/jsonld.js/pull/123>.

However, I'm not sure if I've figured running the local tests correctly. Executing `make test-suite JSONLD_TEST_SUITE=./tests` does it, but all the remote tests fails with `jsonld.InvalidUrl: URL could not be dereferenced: Not Found`. Is the test broken or is my test runner configuration broken? The test I've added passes.

**Comment by dlongley** [comment]
@davidlehn -- we need to see what we can do about adding this local test (make sure it's in the right spot and nothing is misbehaving, etc.) Hopefully we can make a quick tweak or two to make it easier for people to add new local tests as well.

**Comment by jindrichmynarz** [comment]
@dlongley: Is there anything I can do to improve #123? Is it OK to merge the pull request?

**Comment by davidlehn** [comment]
@jindrichmynarz: Merged and released. Thanks.
