### ISSUE TITLE
toRDF() application/n-triples support

### ISSUE THREAD

**Issue by dvh** [digitalbazaar/jsonld.js#124]
Hi,

As far as I can see, the toRDF() method currently only supports `application/nquads` as the `format` option. Some triplestores don't work with `application/nquads` but require `application/n-triples` (without a graph at the end of each line). Is there a way to ignore this last part of the line and thus generate `application/n-triples` instead? At the moment I just generate the quads and use a regular expression to get rid of the graphs :-)

Regards, Dimitri

**Comment by dlongley** [comment]
There are no plans to add N-triples in this library, but we would be happy for someone else to create another library that integrates with jsonld.js that performs this function -- and we'd add something to the README for using it. Closing.
