### ISSUE TITLE
Reason for so many 'throws'?

### ISSUE THREAD

**Issue by viztastic** [digitalbazaar/jsonld.js#125]
I am using jsonld in my express application and seeking to transform errors through middleware (ironically to make the errors semantically meaningful) but I can't seem to control the errors as they seem to get thrown.

Is there a reason for this? Here's a contrived example of one that I'd like to contain in middelware:

![image](https://cloud.githubusercontent.com/assets/8556736/12355293/c0c48c92-bbef-11e5-95b2-03a7def9c45c.png)

**Comment by viztastic** [comment]
For completeness.. this is how I wanted to transform the errors thrown by JSONLD:

```javascript
    var hydra_http = require('hydra-http);

    api_Public.route('/')
            .all(jwt(jwtApiPublicConfig))
            .get(function(request, response, next) {
                
                var doc                     =   {};
                doc["@id"]                  =   request.originalUrl;
                doc[contexts.keys.title]    =   "Welcome to the Salis Api";
                            
                    jsonld.compact(doc, context, function(err, compacted) {
                        if(err) {
                                
                            var errorDetails = {
                                title: err.name,
                                description: err.message + " " + (err.details != null ? err.details : "")
                            }
                            var new_error = new hydra_http.NotFound(errorDetails);
                            next(new_error);
                        } else {
                            logger.debug(compacted);
                            response.json(compacted);
                        }
                    });
            });

```

**Comment by dlongley** [comment]
@viztastic,

How you're handling jsonld.js errors is just fine. That error in your image, however, is not thrown by jsonld.js. It's a top-level script error. You have not defined the variable `context` in your script. The error is being thrown before `jsonld.compact` is called.

**Comment by viztastic** [comment]
Ok that makes perfect sense if the throws are reserved for the top level errors. Much appreciated @dlongley
