### ISSUE TITLE
Using jsonld.js in Node-RED (with browserify)

### ISSUE THREAD

**Issue by KMax** [digitalbazaar/jsonld.js#128]
I use the library as a part of my .js file which is compiled with browserify. The input file for browserify is below and the output file is called `bundle.js`:

```
"use strict";

... // other imports via require(...);
global.JSONLD = require('jsonld');
```

When I import `bundle.js` in .html file which is a part of any Node-RED plugin and do `console.log(JSONLD);`, in the console I see an empty object, i.e. `Object {}`. But if I import the file in a plain HTML outside of Node-RED environment, the library works correctly, i.e. it's imported as a function.

Other libraries which I import in the same way, in example [N3.js](http://github.com/RubenVerborgh/N3.js/) and [axios](https://github.com/mzabriskie/axios), work correctly in both cases.

It's just my guess, but probably the issue is in the way the library is [exported](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L8080).

**Comment by KMax** [comment]
I found a workaround which unfortunately requires to make small changes in the source code of [jsonld.js](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js).

* comment out lines 8060 - 8079
* add `var factory = wrapper({});` before line 8080
* comment out lines 8081 - 8091

After these changes, import the library with `... = require('./jsonld.js');` and the code will work in the both cases mentioned earlier.

**Comment by elf-pavlik** [comment]
I stumbled upon the same issue and patch proposed in previous comment solved it.

@nopnop I remember that you fixed browserify compatibility before in #56, could you imagine taking a look at this issue?

**Comment by nopnop** [comment]
Hi @elf-pavlik,

Sorry for the late answer (I've seen your notification but I should have been distracted at the time).
I've pushed a PR that is, maybe, an acceptable solution to the browserify support issues.

**Comment by dlongley** [comment]
Closing as very old and the landscape has changed -- or this may now potentially duplicate #399 in some way.
