### ISSUE TITLE
Where is verification for "loading an unknown type raises loading document failed"?

### ISSUE THREAD

**Issue by ariutta** [digitalbazaar/jsonld.js#129]
I don't understand how [this JS code](https://github.com/digitalbazaar/jsonld.js/blob/e63baf5efb394b327ce7eff8e079df6cd87e9d0a/js/jsonld.js#L1790) passes [this test](https://github.com/json-ld/json-ld.org/blob/b2c57989c1d72faf5d6fe788c0523120d8098136/test-suite/tests/remote-doc-manifest.jsonld#L34). I don't see any code verifying that the content type of the response is correct.

(Moved the issue over from the json-ld.org repo: https://github.com/json-ld/json-ld.org/issues/410)

**Comment by dlongley** [comment]
@ariutta,

The jsonld.js processor accepts content if it can be parsed as JSON:

https://github.com/digitalbazaar/jsonld.js/blob/e63baf5efb394b327ce7eff8e079df6cd87e9d0a/js/jsonld.js#L276-L293

https://github.com/digitalbazaar/jsonld.js/blob/e63baf5efb394b327ce7eff8e079df6cd87e9d0a/tests/test.js#L671-L676

That test provides content that cannot be parsed as JSON (regardless of the content type presented), so it fails to load -- which causes the test to pass.

**Comment by ariutta** [comment]
That makes sense. Thanks for the explanation.

I'm trying an experiment to see whether the library [superagent-cache](https://github.com/jpodwys/superagent-cache) could be a solution for issue #127.

When there is not response, `superagent` returns an empty `object` as `res.body` instead of `null`, which caused the test to not pass. I was able to change that [here](https://github.com/ariutta/jsonld-rx/blob/5b1422e4906f0e35da3e3fcac29e457a68dc65aa/lib/after.js#L101) so it now passes.

**Comment by dlongley** [comment]
@ariutta,

Ah, ok, makes sense.

**Comment by dlongley** [comment]
@ariutta,

There is also this: https://www.npmjs.com/package/cached-request

Which supposedly works with `request` -- which the node.js document loader is presently using.
