### ISSUE TITLE
@list compaction could maybe work in more cases?

### ISSUE THREAD

**Issue by darobin** [digitalbazaar/jsonld.js#131]
I hit a compaction case which triggered the [JSON-LD compact error](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L2591) exception. I understand that in the general case you can't compact because if the lists differ you can't know which one to pick or what order to use if they were to be merged, and there are no LoLs. I know that the spec directly flags this as an error — I am however interested in discussing it in an implementation context before thinking about spec-side things.

This behaviour is annoying because it prevents switching between heavily denormalised and flattened views when `@list` is involved. Is there a good reason not to support the case in which the two lists are precisely identical, compacting just to that?

**Comment by dlongley** [comment]
@darobin,

Could you provide an example for us to explore?

**Comment by darobin** [comment]
Here's a pretty minimal example that's similar to the one that blew up for me:

```js
import jsonld from 'jsonld';

const doc = {
        '@id':    'new-project',
        '@type':  'CreativeWork',
        author: { '@id': 'seb', name: 'Seb', additionalName: ['J'] },
        citation: {
          '@id':    'older-article',
          '@type':  'ScholarlyArticle',
          author: { '@id': 'seb', name: 'Seb', additionalName: ['J'] },
        }
      }
    , ctx = {
        name: 'http://schema.org/name',
        citation: 'http://schema.org/citation',
        author: 'http://schema.org/author',
        additionalName: {
          '@id': 'http://schema.org/additionalName',
          '@container': '@list',
        },
      }
;

doc['@context'] = ctx;
jsonld.flatten(doc, ctx, (err, flat) => {
  if (err) throw err;
  console.log(JSON.stringify(flat, null, 2));
});
```

Basically the same author appears in multiple places in the denormalised tree. Their `additionalName` can take more than one value, it's a `@list`. The list is exactly the same: it could easily flatten to just that — instead it triggers the "list of list" error.

**Comment by dlongley** [comment]
@darobin,

In the RDF data model, those lists are completely independent values (they generate different triples):

http://json-ld.org/playground/#/gist/4c1a1e8df1594a6feb88

```
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "J" .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "J" .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
```

Do you need to use `@list` here (do you need order?) or will `@set` do? If you don't need order, then the above will behave the way you'd like with `@set`:

http://json-ld.org/playground/#/gist/22c5016bc6875bad7c29

**Comment by darobin** [comment]
Right, but that list got copied through framing. Initially there is a single author instance, but it gets embedded. Obviously we could always operate on a flattened graph, but that can get pretty unpleasant in some cases. The fact that you can't roundtrip here is a pretty severe limitation.

And we do need `@list`, people can get a little bit annoyed when you have their names in the wrong order.

**Comment by dlongley** [comment]
@darobin,

> The fact that you can't roundtrip here is a pretty severe limitation.

Hmm, a lot of the power of framing is derived from giving up the roundtripping requirement once something has been framed. You can create output that is more useful to applications when you can do things like duplicate or filter out data with reckless abandon. I understand your point about this particular case, but we would need to find a way to preserve the information that the list is *actually* the same so that we don't screw things up when it isn't (and supporting the latter is more critical).

> Initially there is a single author instance, but it gets embedded.

Can you use some of the other embed features in framing to avoid the double embed (which results in the copy)? Or do you need it embedded in two or more places?

One option here could be to add a special flag to jsonld.js's `compact` call for this particular case. The flag would "de-duplicate" identical lists encountered during compaction. Currently, when the algorithm compacts a list and is ready to add it to its parent node, it will throw an error if the term uses a `@list` `@container` and it already exists on the parent. Essentially, instead of erroring out immediately, the target list would be compared against the existing one, and if it was identical, the target would be dropped and no error raised.

**Comment by darobin** [comment]
I understand that this cannot be fully general to all manners of framing since you could really go crazy, but this is really a straightforward back and forth between essentially fully-denormalised and fully-normalised.

In our case there really is no point in embedding differently. If it gets to that we're better off hiding the JSON-LD behind an API and keeping it flat internally. We're dealing with pretty big trees and authors could easily repeat in dozens of places. And that's just authors. This limitation is single-handledly forcing us to abandon this tooling and hand-roll our flat/framing.

The option you describe is pretty much what we have in mind. Deep-compare the expanded array and just use it if it's the same.

To be fair we care about the LD, but the fact that it maps to the RDF DM is more of a nuisance than anything else ;)

**Comment by dlongley** [comment]
> The option you describe is pretty much what we have in mind. Deep-compare the expanded array and just use it if it's the same.

Yeah, it seems like this would be doable.

> To be fair we care about the LD, but the fact that it maps to the RDF DM is more of a nuisance than anything else ;)

Understood -- and it would be nice to have lists in the RDF DM.

**Comment by darobin** [comment]
Do you want a PR for this feature?

**Comment by dlongley** [comment]
@darobin,

Yes, that would be great. Otherwise we'll get to it when we can.

**Comment by dlongley** [comment]
Closing as no PR happened -- not sure if any existing feature can handle it now, but trying to clean up issues that have lasted for years without progress that don't seem likely to ever be closed.
