### ISSUE TITLE
Expose all properties in promises interface

### ISSUE THREAD

**Issue by letmaik** [digitalbazaar/jsonld.js#134]
I import jsonld like that:

``` js
import {promises as jsonld} from 'jsonld'
```

Now I wanted to use a custom document loader and found that the `.documentLoader` property (which I would use as a fall-back similar to the README examples) is not exposed in the promises interface. So I would now have to do something like:

``` js
import {promises as jsonld, default as jsonldOriginal} from 'jsonld'
```

and then `jsonldOriginal.documentLoader` which is a bit ugly. So, my suggestion would be to make the `.promises` property a full clone of the standard object, just with promises used where relevant.

**Comment by dlongley** [comment]
This should be addressed now, closing. Reopen if need be.
