### ISSUE TITLE
Organize into modules

### ISSUE THREAD

**Issue by letmaik** [digitalbazaar/jsonld.js#136]
I use this library in a browser context and only need a subset of its functionality. It would be great if the different parts of this package are split into separate modules/files (not packages!) such that I can import only certain functionality and have a smaller network footprint. For example, I don't need to run expansion or normalization algorithms and don't need the jquery or node document loaders.

**Comment by dlongley** [comment]
@neothemachine,

This is being worked on in #126.

**Comment by davidlehn** [comment]
Some progress has been made in 0.5.x.  It's still CJS but headed towards more module setup.

**Comment by dlongley** [comment]
Closing as a duplicate of #399.
