### ISSUE TITLE
Proposal: cache frequently used contexts with a HTTP URL in memory

### ISSUE THREAD

**Issue by pietercolpaert** [digitalbazaar/jsonld.js#138]
## Problem

An application has a certain context it understands. When fetching documents from the Web, the first step is to translate this document to its own context, based on this remote context. This happens using this library.

When an application has, e.g., 5 different sources with a different context it fetches documents from, and these sources have a context identified by a URL:
```json
{
  "@context" : "http://myhost/context.json",
  "...":"..."
}
```
Then for each document it fetches from this source, it should refetch the URL over HTTP. With a good HTTP cache such as in any modern browser, this problem should resolve itself automatically, yet on the command line currently, this is a huge bottleneck as #127 is not yet implemented.

When #127 would be fixed, it would only partially fix the problem, as parsing the response of a context over and over again for an application that doesn't want to loose too much time on the LD part.

## Proposal for a fix

I suggest a dedicated context cache within the jsonld-library that for the lifetime of the application, stores the most frequently used contexts in memory. It would act as a private HTTP cache which can work faster: it knows the typical lifetime of the application and can decide to keep all contexts that have a validity longer than the typical lifetime, readily parsed in memory.

```javascript
jsonld.setTypicalLifetime(5*60*1000); //typical lifetime of our user-agent is 5 minutes
```

## Specific demo which would benefit from this

Check out http://linkedconnections.org (click 2 blue pins): it routes your way through the Belgian railway network by downloading JSON-LD documents.

This is a part of the in browser HTTP request log: 
![screenshot from 2016-04-03 10-29-01](https://cloud.githubusercontent.com/assets/347073/14231528/11466436-f987-11e5-8bbf-91285b7434a2.png)

For every HTTP request it retrieves a JSON-LD response, it has to do an extra HTTP request for a context is has already parsed a couple of ms earlier.

**Comment by RubenVerborgh** [comment]
I think your fix is rather specific; `setTypicalLifetime` is extremely specific.

The object-oriented way to solve this is that a `JSONLD` object can be constructed using a `request` function. If not passed, it performs HTTP requests. If passed, it does whatever you want it to do—in this case, cache.

In absence of such a `JSONLD` object, it could just be a property on the global `jsonld` object, similar to [`http.globalAgent`](https://nodejs.org/api/http.html#http_http_globalagent).

**Comment by dlongley** [comment]
There was already a simple, in-memory cache for JSON-LD contexts that, I believe, did what was is being requested here -- and it was disabled because there is no "typical lifetime". This approach was causing trouble, in particular, for contexts that were in development. The purpose of this cache was to avoid repeated requests for certain contexts in a very short period of time.

I should mention that there is also another cache for "active contexts" -- these are contexts that have already been parsed into term definitions and so on. These stay resident in memory to speed up processing and, to my knowledge, this cache has been working nicely.

There are certainly more improvements that could be made to improve the performance of this library, but we have to be careful in what we implement. As @RubenVerborgh mentioned, it's difficult to define "typical" and, when you do, we need to ensure we don't cause disruptions, unexpected behavior, or hard to debug problems for those use cases that fall outside of that range.

**Comment by dlongley** [comment]
@RubenVerborgh,

> The object-oriented way to solve this is that a JSONLD object can be constructed using a request function. If not passed, it performs HTTP requests. If passed, it does whatever you want it to do—in this case, cache.

JFYI - you can already create your own jsonld instance (just call `jsonld()`), create your own default document loader, or pass one in per call. So that should allow anyone to implement custom behavior -- the question is: how can we improve built-in optimizations?

**Comment by RubenVerborgh** [comment]
> JFYI - you can already create your own jsonld instance (just call jsonld()),

Great, that probably means that @pietercolpaert can already implement what he needs :smile:

**Comment by dlongley** [comment]
@pietercolpaert -- btw, your project is really cool!

**Comment by dlongley** [comment]
You can already create your own instance of `jsonld.DocumentCache` and use it in a custom document loader that wraps one of the existing document loaders (we just disabled it in the default loaders):

https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L1571-L1594

Unfortunately, you can't customize the expiry time, which we should add as an option. We could change the first parameter of the constructor to also accept an options object that could include both size and time to live, and potentially other options in the future.

**Comment by pietercolpaert** [comment]
Thanks for the replies! I'll close this issue as no further actions are required on this repo :)
