### ISSUE TITLE
key not compacted when value is empty list

### ISSUE THREAD

**Issue by sballesteros** [digitalbazaar/jsonld.js#140]
See 
http://json-ld.org/playground/#startTab=tab-compacted&copyContext=true&json-ld=%7B%22%40context%22%3A%7B%22prop%22%3A%22http%3A%2F%2Fexample.com%2Fprop%22%2C%22hasPart%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fschema.org%2FhasPart%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40list%22%7D%7D%2C%22hasPart%22%3A%5B%5D%2C%22prop%22%3A%7B%22hasPart%22%3A%5B%22http%3A%2F%2Fexample.com%22%5D%7D%7D&frame=%7B%7D for an example in the playground:
## Input

``` json
{
  "@context": {
    "prop": "http://example.com/prop",
    "hasPart": {
      "@id": "http://schema.org/hasPart",
      "@type": "@id",
      "@container": "@list"
    }
  },
  "hasPart": [],
  "prop": {
    "hasPart": [
      "http://example.com"
    ]
  }
}
```
## Output (compact)

``` json
{
  "@context": {
    "prop": "http://example.com/prop",
    "hasPart": {
      "@id": "http://schema.org/hasPart",
      "@type": "@id",
      "@container": "@list"
    }
  },
  "prop": {
    "hasPart": [
      "http://example.com"
    ]
  },
  "http://schema.org/hasPart": {
    "@list": []
  }
}
```

Note that the `hasPart` with the empty list value is turned into `http://schema.org/hasPart` instead of `hasPart`.
Totally a weird side case but i wonder if this should be the expected behavior or a bug.

**Comment by dlongley** [comment]
Fixed now, closing.
