### ISSUE TITLE
Wrong MIME type for N-Quads

### ISSUE THREAD

**Issue by miguel76** [digitalbazaar/jsonld.js#141]
According to the W3C Recommendation, the standard MIME type for N-Quads is "application/n-quads" (see https://www.w3.org/TR/n-quads/#h2_sec-mediaReg), while jsonld currently requires "application/nquads" in `.normalize()`, `.toRDF()` and `fromRDF()`.
I propose it should accept both "application/n-quads" and "application/nquads", returning N-Quads in both cases.

**Comment by davidlehn** [comment]
Another attempt at this: https://github.com/digitalbazaar/jsonld.js/pull/223

**Comment by davidlehn** [comment]
Fixed in 0.5.18:
https://github.com/digitalbazaar/jsonld.js/commit/eef1932e96889daa569199d3525bf7ec83119143
