### ISSUE TITLE
Framing fails with predicates beginning with existing id (sh:index+sh:in -> in:dex)

### ISSUE THREAD

**Issue by amiika** [digitalbazaar/jsonld.js#144]
Example in playground:

http://json-ld.org/playground/index.html#/gist/c1c9a32f49f39e4d5d530f54fa829f61

**Comment by dlongley** [comment]
Hmm, strange as this behavior may be, it does conform to the spec algorithms.

"Ties between terms that have the same mappings are resolved by first choosing the shortest terms, and then by choosing the lexicographically least term."
https://www.w3.org/TR/json-ld-api/#term-selection

"...each term in the active context is visited, **ordered by length, shortest first (ties are broken by choosing the lexicographically least term)**."
https://www.w3.org/TR/json-ld-api/#inverse-context-creation

I recommend raising this issue at https://github.com/json-ld/json-ld.org/issues to see what the community thinks about this case.

That first quote could be interpreted to indicate that the terms here don't actually have the same mappings -- or others may indicate that in the context of shortening an `@id`, they do (as `@id` values are unaffected by `@container`). Either way, following the spec algorithms will result in what you're seeing, so this may be errata or it may just be "the right way".

I often find CURIE selection behavior unexpected or undesirable. At this point, I would have preferred we only supported simple terms in the data (but CURIEs are ok in the `@context` for specifying definitions).

**Comment by dlongley** [comment]
Related to https://github.com/json-ld/json-ld.org/issues/405.

**Comment by amiika** [comment]
Ok, makes sense ... kind of. Thanks! :)

In this case i can fix the problem by manually changing the frame, for example: "in"->"valuesIn".

**Comment by amiika** [comment]
I guess i can close this and hope that https://github.com/json-ld/json-ld.org/issues/405 will introduce some option to disable this 'feature'.
