### ISSUE TITLE
Consider adding framing feature to remove unnecessary blank node IDs

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld.js#146]

**Comment by jmatsushita** [comment]
Is this feature meant to serve the following use case?

```
{
  "@context": {"@vocab":"http://example.com/"},
  "@id": "http://example.com/about#gregg",
  "name": "Gregg",
  "knows": [ { "name": "Joe" } ]
}
```

Then when framing (or flattening) the blank nodes are expanded and there is no way to re-obtain the original "unblanked" (what would be the appropriate name for the document without blank node identifier?).

```
{
  "@graph": [
    {
      "@id": "_:b0",
      "http://example.com/name": "Joe"
    },
    {
      "@id": "http://example.com/about#gregg",
      "http://example.com/knows": {
        "@id": "_:b0"
      },
      "http://example.com/name": "Gregg"
    }
  ]
}
```

Is it correct that in fact, if you flatten or frame then currently there are no feature in the API to "unblank" the document or have I missed it?

**Comment by jmatsushita** [comment]
Looking at it a bit more closely it seems that framing (unlinke the flattening example in my previous post) does include the data from the blank node correctly in the framed document.
```
{
  "@graph": [
    {
      "@id": "_:b0",
      "http://example.com/name": "Joe"
    },
    {
      "@id": "http://example.com/about#gregg",
      "http://example.com/knows": {
        "@id": "_:b0",
        "http://example.com/name": "Joe"
      },
      "http://example.com/name": "Gregg"
    }
  ]
}
```

Is "unblanking" a framed document then the same as "recursively" removing blank node `@id`s in the graph? Or are there cases where that won't work?

**Comment by dlongley** [comment]
This feature would remove any blank node IDs that aren't required for reference purposes. In other words, if a blank node ID only occurs once in the output, it would be removed. If it occurs more than once, then we have to persist it so as to avoid breaking links.

**Comment by Prev-I** [comment]
following the Json-LD docs here  https://json-ld.org/spec/latest/json-ld-framing/#dom-jsonldoptions-pruneblanknodeidentifiers

> pruneBlankNodeIdentifiers = true
>     Removes @id from node objects where the value is a blank node identifier used only once within the document.

I think it should be a processor option to be passed at framing function

**Comment by dlongley** [comment]
I believe this is implemented now. Closing.
