### ISSUE TITLE
no bin after installing jsonld.js with node v4.4.5

### ISSUE THREAD

**Issue by greaneym** [digitalbazaar/jsonld.js#147]
Hello, on a mac os,  I used node v4.4.5 to do an npm (v2.15.5) install after following the directions to 
git clone https://github.com/digitalbazaar/jsonld.js.git
Cloning into 'jsonld.js'...
remote: Counting objects: 5617, done.

but after that it did not install jsonld into /usr/local/bin.  

I would like to be able to try out the command line node.js version of jsonld.  What else can I do to make this work please? thanks.

**Comment by mattcollier** [comment]
@greaneym I think you're looking for this repo: https://github.com/digitalbazaar/jsonld-cli

**Comment by greaneym** [comment]
thank you for the response.

**Comment by mattcollier** [comment]
@greaneym you're welcome, can this issue be closed?

**Comment by greaneym** [comment]
yes, thanks for helping me.
