### ISSUE TITLE
compact with lang map produces full URL if no lang

### ISSUE THREAD

**Issue by VladimirAlexiev** [digitalbazaar/jsonld.js#151]
I load [gvp-context.jsonld](https://gist.githubusercontent.com/VladimirAlexiev/6ab60b6a0e1ab32a2f3980c57b005d8f/raw/fca31891bc51b68b34afc77143a886ee3098a4e2/gvp-context.jsonld) and [ulan_500115493_Albrecht_Duerer.jsonld](https://gist.github.com/VladimirAlexiev/6ab60b6a0e1ab32a2f3980c57b005d8f/raw/fca31891bc51b68b34afc77143a886ee3098a4e2/ulan_500115493_Albrecht_Duerer.jsonld) to http://json-ld.org/playground/ and do Compact.

The context declares `rdfs:label` as lang map:
```json
    "rdfs:label" : {"@container": "@language"},
```

There are several labels with lang and many more without, so the result is:
```json
      "rdfs:label": {
        "de": [
          "Dürer, Albrecht",
          "Albrecht Dürer"
        ],
        "ja": "デューラー, アルブレヒト",
        "zh": "阿尔布雷希特·丢勒"
      },
      "http://www.w3.org/2000/01/rdf-schema#label": [
        "Duerer, Albrecht",
        "Albrecht Duerer",
        "Durer, Albrecht",
        "Türer, Albrecht",
```

Why would it emit the full prop URL in the latter case (no lang), instead of the prefixed prop name?

I observed the same defect for data props that are (unnecessarily?) declared `xsd:string` in the context.

**Comment by VladimirAlexiev** [comment]
@azaroth42 pyld (the Python jsonld library) has the same bug, can you post it to their tracker?
Or am I missing something and this fall back to the full prop URL is expected behavior?

**Comment by VladimirAlexiev** [comment]
Maybe I grok why it falls back to the full prop name: a JSON map can't have 2 keys of the same name, so it uses the prefixed name and the full URL as 2 different keys.
But if the context doesn't declare a prefixed name, won't this still cause a conflict?

Ideally, I'd like to see this:

```js
   "rdfs:label": {
        "de": [
          "Dürer, Albrecht",
          "Albrecht Dürer"
        ],
        "ja": "デューラー, アルブレヒト",
        "zh": "阿尔布雷希特·丢勒"
        "": [
          "Duerer, Albrecht",
          "Albrecht Duerer",
          "Durer, Albrecht",
          "Türer, Albrecht",
          ...]
      },
```

**Comment by azaroth42** [comment]
Sadly, propose close invalid. See @gkellogg's response here: https://lists.w3.org/Archives/Public/public-linked-json/2016Sep/0007.html

**Comment by dlongley** [comment]
Yeah, saw the thread. Sorry about the non-intuitive behavior.

**Comment by VladimirAlexiev** [comment]
Maybe I'm too thick, but I don't see how the cited thread answers this. Where does it follow that rdfs:label should be emitted as a full URL?

**Comment by VladimirAlexiev** [comment]
@gkellogg: https://github.com/digitalbazaar/pyld/issues/49 talks about using a default language, and the thread answers that (but not why a full url is used). This issue doesn't talk about a default language.

**Comment by dlongley** [comment]
> Why would it emit the full prop URL in the latter case (no lang), instead of the prefixed prop name?

Because the data does not match the term definition. In order for a particular term to be selected for some particular value, that value must be compatible with the term definition. If no language is given for a particular string, then it cannot be used in a language map. As a side note, the empty string (`""`) cannot be used easily as a key in certain languages, such as PHP (silly, but true, and this threw a wrench into the works during the design phase).

**Comment by gkellogg** [comment]
We probably need additional text in the syntax document (which is what most people will read) about how terms are selected (or not) based on content matching. I know this crosses over to the API document, but it's a common enough issue that it needs to be highlighted.

**Comment by azaroth42** [comment]
"UND" could be used instead of "" ... but then it would work out of the box, as each langString would have a language ... UND.  

Agree that language maps in the documentation could benefit from some additional clarifications.

**Comment by VladimirAlexiev** [comment]
@dlongley So the policy is "use a definition if all its features match". But a more useful policy would be "Use those features from a definition that match".

If I specify a second definition, including only a prefixed name (I guess in a cascaded context), will this be picked up?

@azaroth42 The trouble with "UND" is that RDF statements don't have strict "types" but only per-instance or per-datasource "shapes". Eg SKOS doesn't define the range of skos:prefLabel. So there is no info to which literals to tack "UND" or not. Search by exact literal is fast in all repos I know, and it's very important to keep it that way. If we start playing with UND, a user may end up having to search for eg "foo" and "foo"@UND which will cause endless aggravation.

**Comment by dlongley** [comment]
@VladimirAlexiev,

> So the policy is "use a definition if all its features match". But a more useful policy would be "Use those features from a definition that match".

The problem with the latter approach is that it changes the interpretation of the data. Also, to clarify, I wouldn't say the policy is to "use a definition if all its features match", but rather, "use the a definition if it is compatible and if there's more than one option, use the closest match."

More specifically: https://www.w3.org/TR/json-ld-api/#term-selection

> If I specify a second definition, including only a prefixed name (I guess in a cascaded context), will this be picked up?

If your new definition uses a term with the same name then it "redefines" the term completely. The new definition will only apply at the level in the tree where the new definition is declared (and deeper). If you selectively applied compaction to some area of the tree using such a context, the term would be picked up.

**Comment by azaroth42** [comment]
I don't follow the UND argument, I'm afraid. In SPARQL, language is a filter. So requiring a search for both foo and foo@UND wouldn't be required. The literals would change type from `xsd:string` to `rdf:langString` but I don't see what problem that would cause unless people were explicitly searching for xsd:string (and ... don't do that then).

**Comment by VladimirAlexiev** [comment]
`?x :prop “foo”` and `?x :prop “foo”@UND` and a union thereof is fast, because repos intern URLs and literals like Lisp interns symbols.

 

In comparison, this is very slow:

```sparql

?x :prop ?y.

filter (str(?y)=”foo” &&  lang(?y)=”und”)

```

**Comment by dlongley** [comment]
If we did anything with `UND`, I would expect it to be an artifact of the syntax. It shouldn't impact the data model.
