### ISSUE TITLE
How to combine with TypeScript?

### ISSUE THREAD

**Issue by lgleim** [digitalbazaar/jsonld.js#157]
TypeScript is the future. It eliminates all kinds of errors during development and makes working with typed data easier then ever. Is there any work being done on interfacing json-ld with typescript? I.e. generating typescript classes based on the schema.org definitions and encoded using json-ld? 
Is TypeScript support of interest to the future of the library? What could you imagine to be next steps in order to integrate the two systems?

**Comment by dlongley** [comment]
There are no plans to integrate with TypeScript at this time.

> ...generating typescript classes based on the schema.org definitions and encoded using json-ld?

This may be interesting, but it sounds like a separate project; I don't think it would be part of a core JSON-LD processor.

**Comment by tobiasschweizer** [comment]
This questions is exactly about what I am interested in!

See my post: http://stackoverflow.com/questions/43373824/typescript-interface-formally-describing-an-object-conforming-to-json-ld

I am looking for some way to *formally* specify how an API response in JSON-LD looks like. And for that, TypeScript is ideal in combination with Angular 2!

**Comment by steffansluis** [comment]
I made [a library](https://github.com/knowledge-express/rdf-tools) that does some things like this. At the moment it is very much a work in progress. I use it as a CLI to convert my ontology (defined in seperate `.ttl` files) into:
- A JSON-LD context (in TS, for easy importing).
- TS types for all of the classes in the ontology.
- A flattened version of the ontology for typed referencing of iris.

Again, very much a work in progress that is mostly designed to work for my particular use cases, but I'm open to suggestions/PRs!

**Comment by Eyas** [comment]
@lgleim for Schema.org, [https://github.com/google/schema-dts](google/schema-dts) might help, and would work with jsonld.js since it's just JSON-LD object literal typings.

**Comment by bradjonesca** [comment]
@Eyas  ... link doesn't work

**Comment by Eyas** [comment]
@bradjonesca woops fixed

**Comment by dlongley** [comment]
Closing as other projects seem to be attempting to address this.
