### ISSUE TITLE
Performance problem with simple context test.

### ISSUE THREAD

**Issue by jmatsushita** [digitalbazaar/jsonld.js#163]
While testing for mcollina/levelgraph-jsonld#47 I traced the source of the issue to a performance problem with expansion with this simple case:
```
{
  "@context": "https://schema.org/",
  "name": "BigBlueHat"
}
```

I'm doing a PR in the `test-suite` now.

**Comment by jmatsushita** [comment]
Can't reproduce in the CI. Looks like this is a problem in my development environment.
I use `OSX 10.12.2` and `node v6.9.1`

Using `nvm` I can also reproduce execution times of `3877ms` for `node v5.12.0` `3828ms` in `v4.4.4` while all the other tests run fine performance wise.

**Comment by jmatsushita** [comment]
Well I can't reproduce the timeout but actually looking more closely at the CI logs it is very slow just short of triggering a mocha timeout:
[node 6](https://travis-ci.org/digitalbazaar/jsonld.js/jobs/191876084#L699)
```
  ✓ #t0079 Test jsonld.js timeout problem (1221ms)
```

[node 5](https://travis-ci.org/digitalbazaar/jsonld.js/jobs/191876083#L529)
```
  ✓ #t0079 Test jsonld.js timeout problem (4225ms)
```

**Comment by dlongley** [comment]
Closing as not reproducible. Likely related to loading schema.org context from the net.
