### ISSUE TITLE
Remove dependency on `pkginfo`

### ISSUE THREAD

**Issue by blakeembrey** [digitalbazaar/jsonld.js#168]
It seems pretty unneeded since you could just require the `package.json` yourself and expose the version. However, in my case, I'm having trouble using this module in the context of Runkit (see https://runkit.com/blakeembrey/json-ld-issue). The reason I'm trying to expose it there is that I'd really love to get a demo of https://github.com/blakeembrey/node-scrappy working and I'm using `jsonld` to expand the JSON before extracting the snippets.

Related to https://github.com/blakeembrey/node-scrappy/issues/13.

**Comment by tolmasky** [comment]
Just a heads up, this because pkginfo is a peer dependency. If you require pkginfo you can get it working in RunKit today.

**Comment by blakeembrey** [comment]
I'll give it a go. It's listed in dependencies for me though (https://github.com/digitalbazaar/jsonld.js/blob/0a7b8ba26b2d51c6cc5d784ce5e2d92ec13e4645/package.json#L29), unless we're looking at different things.

**Comment by tolmasky** [comment]
Sorry for the delay, but this should work now. Was our thing.

**Comment by davidlehn** [comment]
Fixed in https://github.com/digitalbazaar/jsonld.js/commit/17ec94a97a11576d319db643829f720db821d8a1 and released in 0.5.17.
