### ISSUE TITLE
Framing ignores @container

### ISSUE THREAD

**Issue by alien-mcl** [digitalbazaar/jsonld.js#191]
I've stumbled on an issue with `@container` being ignored for some situations.
Like in this [link](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22%40context%22%3A%7B%22%40vocab%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fhydra%2Fcore%23%22%2C%22hydra%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fhydra%2Fcore%23%22%2C%22entrypoint%22%3A%7B%22%40id%22%3A%22hydra%3Aentrypoint%22%2C%22%40type%22%3A%22%40id%22%7D%7D%7D%2C%22%40id%22%3A%22%2Fapi%3Fdocumentation%22%2C%22entrypoint%22%3A%7B%22%40id%22%3A%22%2Fapi%22%2C%22%40type%22%3A%22EntryPoint%22%7D%7D&frame=%7B%22%40context%22%3A%7B%22iri%22%3A%22%40id%22%2C%22isA%22%3A%7B%22%40id%22%3A%22%40type%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fhydra%2Fcore%23%22%2C%22hydra%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fhydra%2Fcore%23%22%2C%22operations%22%3A%22hydra%3Aoperation%22%2C%22entryPoint%22%3A%7B%22%40id%22%3A%22hydra%3Aentrypoint%22%7D%7D%7D&context=%7B%7D), you can notice that the `isA` property is framed to a literal but the framing context clearly shows a `"@container": "@set"` declaration.
I'd expected that property to be framed as an array. Am I correct?

**Comment by elf-pavlik** [comment]
equivalent issue in the json-ld specs repo: https://github.com/json-ld/json-ld.org/issues/512

**Comment by dlongley** [comment]
This should be addressed now, closing. Please re-open if still broken.
