### ISSUE TITLE
per property default language

### ISSUE THREAD

**Issue by eroux** [digitalbazaar/jsonld.js#196]
I find it a bit strange not to be able to find any example of such thing, but I would like to have a per-property language default in the `@context`. As an example ([playground link](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22bdr%3AW12837%22%2C%22%40type%22%3A%22bdo%3AWork%22%2C%22bdo%3AworkScanInfo%22%3A%7B%22%40language%22%3A%22en%22%2C%22%40value%22%3A%22bla%22%7D%7D%5D%2C%22%40context%22%3A%7B%22bdo%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2F%22%2C%22adm%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fadmin%2F%22%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%7D%7D&frame=%7B%22%40context%22%3A%7B%22bdo%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2F%22%2C%22workScanInfo%22%3A%7B%22%40language%22%3A%22bo%22%2C%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2FworkScanInfo%22%7D%7D%2C%22%40type%22%3A%22bdo%3AWork%22%7D&context=%7B%7D)):

Initial doc:

```
{
  "@graph" : [ {
    "@id" : "bdr:W12837",
    "@type" : "bdo:Work",
    "bdo:workScanInfo" : {
      "@language" : "en",
      "@value" : "bla"
    }
  } ],
  "@context" : {
    "bdo" : "http://purl.bdrc.io/ontology/",
    "adm" : "http://purl.bdrc.io/ontology/admin/",
    "xsd" : "http://www.w3.org/2001/XMLSchema#"
  }
}
```

Framing doc:

```json
{
  "@context": {
    "bdo" : "http://purl.bdrc.io/ontology/",
    "workScanInfo" : {
      "@language" : "bo",
      "@id": "http://purl.bdrc.io/ontology/workScanInfo"
    }
  },
  "@type": "bdo:Work"
}
```

What I would expect is `workScanInfo` to have no `@language` tag when the lang is "bo" (which works fine):

```json
      "workScanInfo":  "bla"
```

but to have one when the lang is not "bo":

```json
      "workScanInfo": {
        "@language": "en",
        "@value": "bla"
      }
```

but Instead the playground does not use `workScanInfo` but uses `bdo:workScanInfo` instead:

```json
      "bdo:workScanInfo": {
        "@language": "en",
        "@value": "bla"
      }
```

is there a reason for that? I've looked into the spec but wasn't able to find any particular reason why my idea wouldn't work.

**Comment by dlongley** [comment]
If this feature is still desired it should be opened on the cg/wg issue tracker where an existing solution may be proposed or it may fall under a new feature request. Closing here.
