### ISSUE TITLE
bug in IRI compaction (@vocab precedence not strong enough)

### ISSUE THREAD

**Issue by eroux** [digitalbazaar/jsonld.js#197]
Following https://github.com/json-ld/json-ld.org/issues/526 : [this example](https://json-ld.org/playground/#startTab=tab-compacted&copyContext=true&json-ld=%7B%22%40context%22%3A%7B%22%40vocab%22%3A%22http%3A%2F%2Fvocab.getty.edu%2F%22%2C%22a%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faaaaaaaaaat%2F%22%7D%2C%22%40id%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faaaaaaaaaat%2F5001065997%22%2C%22%40type%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faaaaaaaaaat%2Fdatatype%22%7D) should output `aaaaaaaaaat/datatype` instead of `a:5001065997`. This is particularly ugly and unpleasant, but that's point `3)` of URI Compaction in the [spec](https://www.w3.org/TR/json-ld-api/#iri-compaction)

**Comment by dlongley** [comment]
This was transferred to the WG and resolved as "won't fix". Closing.
