### ISSUE TITLE
JSON-LD Playground does not accept language container in @context

### ISSUE THREAD

**Issue by nitmws** [digitalbazaar/jsonld.js#202]
I've put this @context into the New JSON-LD Context textbox of the JSON-LD Playground:
```
{
 "@context": {
    "skos":    "http://www.w3.org/2004/02/skos/core#",

    "prefLabel":        {"@id": "skos:prefLabel", "@container": "@language"}
  }
}
```
and get a note that something does not fit: "allOf/2/additionalProperties/anyOf: Data does not match any schemas from "anyOf"

Note: my context is based on https://www.w3.org/TR/json-ld/#string-internationalization - Example 34.

**Comment by davidlehn** [comment]
That was a warning due to `@language` missing from the schema.  Output was still ok.  Fixed:
https://github.com/json-ld/json-ld.org/commit/019de59e296c39d7b5c0298d49d95b99fceb294a
