### ISSUE TITLE
What kind of http response for context resources is required by the Playground?

### ISSUE THREAD

**Issue by nitmws** [digitalbazaar/jsonld.js#204]
I'm working on a solution as outlined in JSON-LD 1.1 4.9: https://json-ld.org/spec/latest/json-ld/#interpreting-json-as-json-ld and I try to test it on the JSON-LD Playground.
The context resides at https://www.iptc.org/std-dev/NewsCodes/IKOS/IKOS.jsonld - but inserting this URL into the field next to New JSON-LD Context of the Playground results in a "Error loading context URL: https://www.iptc.org/std-dev/NewsCodes/IKOS/IKOS.jsonld" without any note on what kind of error occurred.
To find the reason for this error that I've:
* put the object of the context resource into the News JSON-LD Context textbox: no error, I assume the syntax is correct. The Playground has not problems with an example JSON for the graph.
* checked the response of the web server delivering the context resource: 
![ikos-context-2017-10-24_15-29-59](https://user-images.githubusercontent.com/1301232/31953252-00267ade-b8e3-11e7-9be7-118ca82385d2.jpg)
* and compared it to the context resource of schema.org: 
![schema org-context-2017-10-24_17-08-11](https://user-images.githubusercontent.com/1301232/31953287-154d877c-b8e3-11e7-907a-a576ded362d3.jpg)

* The Media Type of the response is the same (application/ld+json), the encoding/charset is the same. 

I can't see any further hint on why the Playground does not like the IKOS context resource.

**Comment by elf-pavlik** [comment]
looks like you don't have CORS headers https://github.com/json-ld/json-ld.org/issues/366

**Comment by nitmws** [comment]
Yup, adding
`Header set Access-Control-Allow-Origin *`
to the .htaccess is what the Playground needs.
