### ISSUE TITLE
What version is the real latest release?

### ISSUE THREAD

**Issue by nitmws** [digitalbazaar/jsonld.js#208]
I checked on npmjs if an update of jsonld.js is available but there version 0.4.12 is shown - https://www.npmjs.com/package/jsonld - which I have already installed.
Then I had a look into this repository and saw 0.5.15 as latest release.
Are the versions above 0.4.12 beta versions or is there another reason for the version gap between this Github repository and the module posting at npmjs.com ?
(I have tried to install 0.5.15 with npm - and it worked ... a surprise.)

**Comment by davidlehn** [comment]
0.4.x is the "latest" release.  0.5.x is under development and may have breaking changes between patch releases until we decide it's stable enough to move to the "latest" tag.

Progress and a hopeful TODO list is mostly tracked here:
https://github.com/digitalbazaar/jsonld.js/pull/194

**Comment by nitmws** [comment]
Ok, clarified.
