### ISSUE TITLE
Nested properties not implemented

### ISSUE THREAD

**Issue by jmvanel** [digitalbazaar/jsonld.js#215]
Example 76: Nested properties
https://json-ld.org/spec/latest/json-ld/#nested-properties
fails in Playground:

    "message": "Invalid JSON-LD syntax;
    a @context @id value must be an absolute IRI, a blank node identifier, or a keyword.",

Moreover , the Playground should **not** claim:
 _The playground uses the jsonld.js JSON-LD processor which fully conforms to the JSON-LD Syntax_

**Comment by davidlehn** [comment]
The "latest" doc has many new JSON-LD features not yet in a published spec.  The playground uses a version of jsonld.js that only supports JSON-LD 1.0.  Support for new features is currently being worked on.

**Comment by davidlehn** [comment]
1.0.0 released supporting 1.1 draft features.
See https://github.com/digitalbazaar/jsonld.js#conformance.
There is now also a "dev" playground using 1.0.0.
