### ISSUE TITLE
Preserve graph names when converting to RDF

### ISSUE THREAD

**Issue by steffansluis** [digitalbazaar/jsonld.js#216]
According to the [spec](https://json-ld.org/spec/latest/json-ld/#named-graphs), converting a JSON-LD document to quads results in quads labeled with the graph name. The library instead creates anonymous named graphs. Is there a particular reason why the resulting quads are not labeled with the graph names from the document?

**Comment by gkellogg** [comment]
As [this playground example](http://tinyurl.com/ybl7b6hu) shows, graph names _are_ preserved. However, if the graph is named with a blank node, that particular label is not preserved, as blank node labels are not part of the data model.

**Comment by steffansluis** [comment]
I seem to have missed something. Thank you very much for the quick response! Also great library! :smiley:
