### ISSUE TITLE
bug (typo) in jsonld.fromRDF for back-compat with old parsers that produced legacy dataset format

### ISSUE THREAD

**Issue by sballesteros** [digitalbazaar/jsonld.js#229]
See https://github.com/digitalbazaar/jsonld.js/blob/a73f1396353ed87ac95f8cc89d775402498c5bdd/lib/jsonld.js#L611-L613

I believe that

```js
    parsedDataset = NQuads.legacyDatasetToQuads(dataset);
```
should be

```js
    parsedDataset = NQuads.legacyDatasetToQuads(parsedDataset);
```

**Comment by davidlehn** [comment]
Thanks.  Fixed in 0.5.20 with https://github.com/digitalbazaar/jsonld.js/commit/04e06802406bb962da53964dfb8fe97b59bb2b52.
Note that we don't have tests for this, so let us know if it doesn't work.
