### ISSUE TITLE
Confusing error message when frame doesn't match document (for @list)

### ISSUE THREAD

**Issue by mittinatten** [digitalbazaar/jsonld.js#238]
Hi,
When you have a frame that specifies a simple property:

~~~~json
{
  "@context": { "ex": "http://example.org/"},
  "ex:foo": { "@type": "ex:bar"}
}
~~~~

but the document you're framing has that property in a list:

~~~~json
{
  "http://example.org/foo": {
    "@list": [ 
      {
      	"@type": "http://example.org/bar"
      }
    ]
  }
}
~~~~

You get the following error message: `jsonld.SyntaxError: Invalid JSON-LD syntax; a JSON-LD frame must be a single object.`. This is quite confusing, since it's not a syntax error but a mismatch between frame and data.

Example at JSON-LD playground:
http://tinyurl.com/ydyern27

**Comment by dlongley** [comment]
This is fixed, closing.
