### ISSUE TITLE
Why it requires PYTHON to be installed?

### ISSUE THREAD

**Issue by Kish-Jadhav** [digitalbazaar/jsonld.js#240]
Why this library has dependency on PYTHON? I  want to understand the where is it's dependency.

My use case is : I want to transform JSON to JSON-LD. To do this, i am trying to use this library.

**Comment by davidlehn** [comment]
It doesn't depend on Python.  What version are you using?  What transformation are you doing?  JSON-LD is just JSON with a particular semantic structure.

**Comment by Kish-Jadhav** [comment]
Apologies for delayed reply..
I am using "jsonld": "^1.0.1", npm module. The purpose using this library is: Transform JSON into JSON LD format. I can see  JSON
LD module page on NPM site which has dependency on 'rdf-canonize' there it is giving me an error:

> rdf-canonize@0.2.3 install F:\Kish\OSLC\Ajay\jsontransformer\jsontransformer\node_modules\rdf-canonize
> node-gyp rebuild


<My_PRO_DIR>\node_modules\rdf-canonize>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd <My_PRO_DIR>\node_modules\rdf-canonize
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by Kish-Jadhav** [comment]
Any thoughts on it? My use case is simple - I want to transform JSON into JSONLD format and for that I don't think we need PYTHON installed.

**Comment by mattcollier** [comment]
Can you say more about what you are trying to do?  This library is used to perform various operations on JSON-LD documents as demonstrated here: https://json-ld.org/playground/

Can you explain what you mean by transforming JSON into JSON-LD?  Because this library doesn't actually do that, that is done by essentially specifying a `context` property in your JSON object and making sure that all the other properties of the object are defined in that context.

**Comment by manniL** [comment]
@Kish-Jadhav this dependency is not related to the library, but to [`node-gyp`](https://github.com/nodejs/node-gyp).

**Comment by Jimflip** [comment]
The node-gyp is pulled in by the rdf-canonize module, and the build dep is discussed in this issue:
https://github.com/digitalbazaar/rdf-canonize/issues/5
