### ISSUE TITLE
Document how to serialize Turtle

### ISSUE THREAD

**Issue by nichtich** [digitalbazaar/jsonld.js#250]
The documentation illustrates how to serialize N-Quads syntax but does not mention other serialization forms. In particular it should illustrate how to convert to Turtle syntax because this is required by <https://www.w3.org/TR/ldp/> in addition to JSON-LD.

This issue seems to be the reverse of #108.

**Comment by linonetwo** [comment]
So actually it can serialize to turtle?

**Comment by elf-pavlik** [comment]
You could use turtle module from http://rdf.js.org/

**Comment by dlongley** [comment]
There's no plan to add serialization to Turtle in this library -- but we'd be happy to accept a PR that showed how to integrate this library with another one that does so.
