### ISSUE TITLE
Failed node-gyp in C++ error

### ISSUE THREAD

**Issue by Carpani** [digitalbazaar/jsonld.js#254]
Hello, i'm trying to install json-ld and fail to install rdf-canonize  width:

**../lib/native/NQuads.cc:75:53: error: no hay una función coincidente para la llamada a ‘regex_replace(std::string&, std::regex&, const char [3])’
     escaped = regex_replace(escaped, REGEX_CR, "\\r");**

The same happend with all regex_replace calls.

I'm using:
Node 8.11
Npm 6.1
node-gyp 0.2.5
gcc-c++ 4.8.5-28

In a Centos 7.3.

Some solution?

Thanks
FDO.

**Comment by davidlehn** [comment]
regex_replace is from C++11 so you need g++ 4.9 or greater.

**Comment by Carpani** [comment]
Thanks.
Solved.
FDO.
