### ISSUE TITLE
Converting JsonLd to RDF/XML or Turtle

### ISSUE THREAD

**Issue by przemko1984** [digitalbazaar/jsonld.js#255]
Is it possible to convert Json-Ld data to different format like RDF/XML, Turtle or N3?

I tried to use `rdf-parser-rdfxml` for RDF/XML:
```
  const parser = () => new RdfXmlParser();
  jsonld.registerRDFParser('application/rdf+xml', parser);

  return await jsonld.fromRDF(dataBody, { format: 'application/rdf+xml' }); 
```
(and some other combinations, but it doesn't work)

My goal is to create converter in both directions between Json-Ld and RDF/XML, N3, Turtle

Maybe somebody know some of the existing parsers that could be used for converting in both directions.

**Comment by elf-pavlik** [comment]
You can do it with more general RDF tool like https://github.com/rdf-ext/rdf-ext#modules

**Comment by gkellogg** [comment]
You can also use an online tool such as my own at http://rdf.greggkelllogg.net/distiller

**Comment by przemko1984** [comment]
Hey, @elf-pavlik 

> You can do it with more general RDF tool like https://github.com/rdf-ext/rdf-ext#modules

Some time ago we used this tool for converting from different formats (RDX/XML, N3, Turtle) to JSON-LD, but it looks like we can not use it for converting in opposite direction (from JSON-LD). Do you know is it possible?

> https://www.w3.org/community/rdfjs/2018/04/23/rdf-js-the-new-rdf-and-linked-data-javascript-library/

thanks for notification

hey, @gkellogg 

> You can also use an online tool such as my own at http://rdf.greggkelllogg.net/distiller

Thx, I saw this approach as well, but we cann't afford for using online tool

**Comment by elf-pavlik** [comment]
@bergos have published some examples here https://github.com/rdf-ext/rdf-examples
Examples of parsing and serializing should work with any combination of parsers and serializers e.g
parse: https://github.com/rdf-ext/rdf-parser-jsonld
serialize: https://github.com/rdf-ext/rdf-serializer-n3

Since `0.5.15` jsonld.js uses RDFJS format internally and N3.js uses it as well since `1.0`, I don't know if rdf-ext parses and serializes using those two libraries got updated to take advantage of that. If not I guess RDF.js crews could prioritize that.

**Comment by bergos** [comment]
@elf-pavlik on my local machine `@rdfjs/parser-jsonld` uses already the latest version of `jsonld.js` and the RDFJS format. You can expect npm releases till end of this week.

**Comment by sanuann** [comment]
what's the final solution to this issue?

**Comment by qertis** [comment]
some problem

**Comment by gkellogg** [comment]
> You can do it with more general RDF tool like https://github.com/rdf-ext/rdf-ext#modules
> 
> Maintainers of rdf-ext, rdflib.js and n3.js plan to converge them into one library RDF.js
> https://www.w3.org/community/rdfjs/2018/04/23/rdf-js-the-new-rdf-and-linked-data-javascript-library/
> 
> It will use jsonld.js to parse and serialize JSON-LD

It should be relatively straightforward, and would be a great integration model, to incorporate jsonld.js into rdflib.js. jsonld.js does not use the core datatypes, but the result of the JSON-LD toRdf algorithm is a dataset, not specifically N-Quads; it only becomes N-Quads when re-serialized, and jsonld.js includes an N-Quads serializer. Same with the fromRdf algorithm, which takes a dataset and returns a JSON-LD serialization.

The "glue" needed would be to transform between jsonld.js' dataset representation (basically, an array of objects, with subject, predicate, object, and graph entries) and that used by another library such as rdflib.js. The fromRdf algorithm just reverses the process.

**Comment by dlongley** [comment]
I'm not sure this issue is actionable -- I'm closing it. If there's an action to be taken, it can be reopened with that clearly expressed.

**Comment by gkellogg** [comment]
What would be useful for developers is guidance in working with rdf.js; surely there's a fairly simple adaptor that could be pint into place.
