### ISSUE TITLE
Framing nested graphs gives an error

### ISSUE THREAD

**Issue by pietercolpaert** [digitalbazaar/jsonld.js#256]
When named graphs are nested in an input document, an unexpected error happens when trying to retrieve the contents of the named graph.

The expected behavior would be that it shows the contents of all graphs.

Reproduce on the JSON-LD playground (dev) using the library and books example from the specification:

https://json-ld.org/playground-dev/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22%40vocab%22%3A%22http%3A%2F%2Fexample.org%2F%22%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fgraphs%2Fbooks%22%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Flibrary%2Fthe-republic%22%2C%22%40type%22%3A%22http%3A%2F%2Fexample.org%2FBook%22%2C%22http%3A%2F%2Fexample.org%2Fcontains%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Flibrary%2Fthe-republic%23introduction%22%7D%7D%2C%7B%22%40graph%22%3A%7B%22http%3A%2F%2Fexample.org%2Fcontains%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fgraphs%2Fbooks%22%7D%2C%22http%3A%2F%2Fexample.org%2Fname%22%3A%22Library%22%7D%7D%5D%7D&frame=%7B%22%40graph%22%3A%7B%7D%7D

Frame:
```json
{"@graph":{}}
```

Input document:

```json
{
  "@context": {"@vocab": "http://example.org/"},
  "@id": "http://example.org/graphs/books",
  "@graph": [
    {
      "@id": "http://example.org/library/the-republic",
      "@type": "http://example.org/Book",
      "http://example.org/contains": {
        "@id": "http://example.org/library/the-republic#introduction"
      }
    },
    {
      "@graph": {
        "http://example.org/contains": {
          "@id":   "http://example.org/graphs/books"
        },
        "http://example.org/name": "Library" 
      }
    }          
  ]
}
```

This gives the error `TypeError: Cannot read property 'http://example.org/library/the-republic#introduction' of undefined`

Source code line that errors: https://github.com/digitalbazaar/jsonld.js/blob/c6501fbf44cd9d5a589212f9428c0573ae40ada2/lib/frame.js#L379

**Comment by pietercolpaert** [comment]
This example with  equal level nested graphs works nonetheless: https://json-ld.org/playground-dev/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22%40vocab%22%3A%22http%3A%2F%2Fexample.org%2F%22%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fgraphs%2Fbooks%22%2C%22%40graph%22%3A%5B%7B%22%40graph%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Flibrary%2Fthe-republic%22%2C%22%40type%22%3A%22http%3A%2F%2Fexample.org%2FBook%22%2C%22http%3A%2F%2Fexample.org%2Fcontains%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Flibrary%2Fthe-republic%23introduction%22%7D%7D%7D%2C%7B%22%40graph%22%3A%7B%22http%3A%2F%2Fexample.org%2Fcontains%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fgraphs%2Fbooks%22%7D%2C%22http%3A%2F%2Fexample.org%2Fname%22%3A%22Library%22%7D%7D%5D%7D&frame=%7B%22%40graph%22%3A%7B%7D%7D

**Comment by davidlehn** [comment]
The frame test tg010 may cover this issue?  It has nested graphs and is failing with same error message.
https://github.com/json-ld/json-ld.org/blob/master/test-suite/tests/frame-manifest.jsonld
https://github.com/json-ld/json-ld.org/blob/master/test-suite/tests/frame-g010-in.jsonld
https://github.com/json-ld/json-ld.org/blob/master/test-suite/tests/frame-g010-frame.jsonld
https://github.com/json-ld/json-ld.org/blob/master/test-suite/tests/frame-g010-out.jsonld

If this use case is different then a new test should be added for it.

jsonld.js/pyld have fallen a bit behind in handling the latest CG/WG drafts and latest test cases.  When we find the time to get in fixes for latest changes and tests it should hopefully resolve this.

**Comment by dlongley** [comment]
This appears to be fixed, closing.
