### ISSUE TITLE
reference implementation needs update to handle relative URIs according to 1.1 spec

### ISSUE THREAD

**Issue by TallTed** [digitalbazaar/jsonld.js#266]
The [example in the updated 1.1 spec](https://www.w3.org/TR/2018/WD-json-ld11-20180911/#using-the-document-base-as-the-default-vocabulary) --

```json-ld
{
  "@context": {
    "@version": 1.1,
    "@base": "http://example/document",
    "@vocab": ""
  },
  "@id": "http://example.org/places#BrewEats",
  "@type": "#Restaurant",
  "#name": "Brew Eats"
}
```

-- still receives an error appropriate to JSON-LD 1.0 --

>`jsonld.SyntaxError: Invalid JSON-LD syntax; the value of "@vocab" in a @context must be an absolute IRI.`

-- instead of being properly parsed by [the JSON-LD 1.1 reference implementation on the Development Playground](https://json-ld.org/playground-dev/).

/cc @smalinin @kidehen

**Comment by dlongley** [comment]
I believe this has been fixed, closing.
