### ISSUE TITLE
Remove use of net/global as Angular 6 no longer supports it

### ISSUE THREAD

**Issue by Aaron-Sterling** [digitalbazaar/jsonld.js#267]
Angular 6 has removed support for net/global, justification [here](https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814).

This has affected several libraries, including this one. There's a polyfill workaround for this, which I didn't invent, but I describe [here](https://github.com/Aaron-Sterling/ngx-jsonld-provider#step-2-add-polyfill-for-angular-6) in installation instructions to an Angular JSON-LD tool. The long-term recommendation, however, from Angular, is for libraries to remove use of net/global.

Therefore, please remove use of net/global when you can.

**Comment by dlongley** [comment]
I think this has been resolved, closing.
