### ISSUE TITLE
Node documentLoader fails on redirected addresses within Jest

### ISSUE THREAD

**Issue by maparent** [digitalbazaar/jsonld.js#269]
The documentLoader explicitly specifies followRedirect: false here:

https://github.com/digitalbazaar/jsonld.js/blob/ce41d4a1e058b8d8fc1dc567446d352d79b3b3fb/lib/documentLoaders/node.js#L71

Use of purl.org is still common in the linked data community, and disabling redirection makes many addresses harder to use.

**Comment by davidlehn** [comment]
I think that's done intentionally as the loader code handles redirects itself.  Check out the "handle redirect" section later in that function.  We use this on purl.org and w3id.org all the time.  Are you finding some condition where the redir code isn't working?

**Comment by maparent** [comment]
Ah, strange. Yes, calling jsonld.processContext directly with a purl url fails for me. Will debug and report back.

**Comment by maparent** [comment]
Still struggling to find the root cause. Basically, the problem happens in jest, not in production code.
Here is an example jest test:
```
test("strangely fails", async () => {
  try {
    const base_ctx = jsonld_context.getInitialContext({})
    const ctx = await jsonld.processContext(base_ctx, "http://purl.org/catalyst/jsonld")
    console.log("reaching success")
  } catch (error) {
    console.log("reaching catch")
  }
})
```

I'm reaching the `success` and not the `catch`, but the test still fails. The `StatusCodeError: 302` still shows (I suspect an unhandled exception, but logging on a unhandledRejection handler does not show up.) I'm currently trying to determine if the RequestQueue breaks the async promise chain along the way.

I'm using jest@23, babel/runtime@7.1, node v10.11.0 on mac os, jsonld@1.1.0, feel free to ask about other components. I'm targetting current node in babel. Feel free to reach out if you have issues reproducing.

**Comment by dlongley** [comment]
Closing as stale, please re-open if necessary.
