### ISSUE TITLE
DocumentLoader in jsonld npm package for flatten

### ISSUE THREAD

**Issue by angshuman** [digitalbazaar/jsonld.js#270]
I would like to use document loader in the flatten method. I have an external context hosted in a public uri. For some reason the download occasionally fails. I would like to use a custom document loader for that URI. Is this possible?

**Comment by davidlehn** [comment]
Sure, something like this (in callback style, async/await works too):
```js
const oldLoader = jsonld.documentLoader;
const customLoader = function(url, callback) {
  if(url === 'https://example.com/url-to-override') {
    // just returning a static local context here, could async load from a file
    return callback(null, {
      contextUrl: null,
      document: aLocalContext,
      documentUrl: url
    });
  }
  oldLoader(url, callback);
};
```
Can then set it to *always* be used:
```js
jsonld.documentLoader = customLoader;
```
Or can just use it for specific calls:
```js
jsonld.flatten(input, ctx, {documentLoader: customLoader, ...}, callback);
```
You can change this to look up a key in a map of contexts, or do whatever else is needed.

**Comment by angshuman** [comment]
Thanks. That works.
