### ISSUE TITLE
Bump rdf-canonize dependency to 0.3

### ISSUE THREAD

**Issue by peacememories** [digitalbazaar/jsonld.js#272]
Since [rdf-canonize](https://github.com/digitalbazaar/rdf-canonize) 0.3 seems to sidestep native build issues, I think it would be great for jsonld.js to update its dependencies, so we can use the new versions in production.

See: https://github.com/digitalbazaar/rdf-canonize/issues/5

**Comment by bushidocodes** [comment]
This update would be useful for me as well. I can't build via Netlify currently because they don't seem to expose a way to make sure I have a modern enough version of GCC.

**Comment by paulirish** [comment]
We're super interested in seeing this get bumped. @davidlehn will you have some time to bump the dep and ship a new version?

**Comment by davidlehn** [comment]
Released 1.2.0 using rdf-canonize 0.3.0.  I had hoped a better solution to the native binding issue would appear but this approach should be an improvement and will do for now.

**Comment by paulirish** [comment]
Such response time! Thanks very much @davidlehn. Really appreciate it :D

**Comment by paulirish** [comment]
@davidlehn We want use jsonld.js within [Lighthouse](https://github.com/GoogleChrome/lighthouse), though we really want to avoid a native module installation step.

While 0.3 sets it up as optional, the compile is still attempted. This includes every user installation and every install on CI. 

Our preference would be to avoid the native module entirely, both for installation speed and so our users don't have to worry about compilation failures, etc.  Does that make sense?

Recommending using `--no-optional` in all our documentation is a very unattractive remedy to us. :/ The most obvious solution I see is to publish jsonld with a different package name and without the optionalDependency. I know this isn't the most attractive solution, but I'm curious about your thoughts.  Thanks

**Comment by davidlehn** [comment]
@paulirish Yup, I understand. The optional dependency change was an effort to improve the immediate problem. We knew the new problem would be bogus confusing compile failures. I guess that's better? ;-)

I'm not really sure what the best approach is to make this situation better. It's rdf-canonize that has the optional dependency on rdf-canonize-native. So to have a different jsonld without the native dependency would require a different rdf-canonize too.  That seems like a route that leads to packaging pain.

Another way is to just remove the optional native dependency and leave it up to higher level apps to install it as needed.  That leaves the default installs as all js.  And the native package is an accelerator you can use if needed.  We didn't do that in the first place because it seems like a challenge to let jsonld users know they now should really install this extra package for performance.  I'm guessing this is the best way forward as the only drawback is slower code and it kicks the problem over to someone else.

Maybe there's a way for the build failures to be more silent?  Not sure how to do that as it's just doing it's thing automatically right now.  Unfortunate this use case is not easier to deal with.

I guess the ideal thing would be that v8 speeds up the js enough that we don't even need the native code. ;-)  The algorithms are not doing anything too crazy so maybe the js could just be optimized to make this all moot.

**Comment by paulirish** [comment]
> I guess the ideal thing would be that v8 speeds up the js enough that we don't even need the native code. ;-)

So I just ran `TEST_DIR=./benchmark npm run benchmark` and it appears JS is already faster than native. I'm seeing more ops/sec for js than native in all block sizes and in both sync and async. I tested in both node 6 and node 10. Node 6 JS has equal performance in JS and native. **In Node 10, JS is 650% faster.** 

<details>
<summary>node 6 results</summary>
<pre>
$ TEST_DIR=./benchmark npm run benchmark

> rdf-canonize@0.3.1-0 benchmark /Users/paulirish/code/temp/rdf-canonize
> node benchmark/benchmark.js

Benchmarking...
RDF Dataset Normalization / #block-1 block-1 / (asynchronous js) x 1,494 ops/sec ±1.60% (79 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (asynchronous js x 10) x 147 ops/sec ±3.20% (77 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (asynchronous native) x 1,488 ops/sec ±2.15% (80 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (asynchronous native x 10) x 149 ops/sec ±2.17% (76 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (synchronous js) x 2,236 ops/sec ±2.91% (80 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (synchronous js x 10) x 226 ops/sec ±2.15% (80 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (synchronous native) x 2,317 ops/sec ±1.60% (82 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (synchronous native x 10) x 229 ops/sec ±2.01% (78 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (asynchronous js) x 570 ops/sec ±2.61% (78 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (asynchronous js x 10) x 58.29 ops/sec ±1.80% (68 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (asynchronous native) x 580 ops/sec ±1.45% (83 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (asynchronous native x 10) x 58.74 ops/sec ±1.84% (71 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (synchronous js) x 1,039 ops/sec ±2.30% (80 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (synchronous js x 10) x 105 ops/sec ±1.66% (78 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (synchronous native) x 1,046 ops/sec ±1.96% (82 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (synchronous native x 10) x 104 ops/sec ±2.34% (78 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (asynchronous js) x 149 ops/sec ±1.68% (83 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (asynchronous js x 10) x 13.37 ops/sec ±4.21% (63 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (asynchronous native) x 146 ops/sec ±2.57% (81 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (asynchronous native x 10) x 13.76 ops/sec ±3.86% (64 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (synchronous js) x 245 ops/sec ±1.59% (77 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (synchronous js x 10) x 25.37 ops/sec ±2.02% (60 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (synchronous native) x 255 ops/sec ±1.59% (80 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (synchronous native x 10) x 25.19 ops/sec ±1.91% (60 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (asynchronous js) x 13.83 ops/sec ±4.63% (64 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (asynchronous js x 10) x 1.47 ops/sec ±4.83% (12 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (asynchronous native) x 13.59 ops/sec ±4.31% (63 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (asynchronous native x 10) x 1.40 ops/sec ±4.20% (11 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (synchronous js) x 25.20 ops/sec ±0.61% (60 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (synchronous js x 10) x 2.51 ops/sec ±2.91% (17 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (synchronous native) x 25.50 ops/sec ±1.80% (60 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (synchronous native x 10) x 2.51 ops/sec ±3.06% (17 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (asynchronous js) x 1.33 ops/sec ±3.77% (11 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (asynchronous js x 10) x 0.14 ops/sec ±1.91% (5 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (asynchronous native) x 1.27 ops/sec ±4.05% (11 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (asynchronous native x 10) x 0.13 ops/sec ±1.71% (5 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (synchronous js) x 2.10 ops/sec ±2.98% (15 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (synchronous js x 10) x 0.21 ops/sec ±1.36% (6 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (synchronous native) x 1.99 ops/sec ±3.25% (14 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (synchronous native x 10) x 0.20 ops/sec ±1.79% (6 runs sampled)
Done.
</pre>

![image](https://user-images.githubusercontent.com/39191/51066575-eff10e00-15bf-11e9-8152-d6ac3d50c410.png)

</details>

<details>
<summary>node 10 results</summary>
<pre>
❯ env TEST_DIR=./benchmark npm run benchmark

> rdf-canonize@0.3.1-0 benchmark /Users/paulirish/code/temp/rdf-canonize
> node benchmark/benchmark.js

Benchmarking...
RDF Dataset Normalization / #block-1 block-1 / (asynchronous js) x 4,089 ops/sec ±0.68% (78 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (asynchronous js x 10) x 420 ops/sec ±0.91% (85 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (asynchronous native) x 373 ops/sec ±0.35% (83 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (asynchronous native x 10) x 117 ops/sec ±3.02% (76 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (synchronous js) x 4,527 ops/sec ±2.41% (75 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (synchronous js x 10) x 524 ops/sec ±0.94% (84 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (synchronous native) x 399 ops/sec ±1.00% (84 runs sampled)
RDF Dataset Normalization / #block-1 block-1 / (synchronous native x 10) x 36.38 ops/sec ±1.64% (76 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (asynchronous js) x 1,323 ops/sec ±3.04% (79 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (asynchronous js x 10) x 140 ops/sec ±0.62% (79 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (asynchronous native) x 245 ops/sec ±0.38% (84 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (asynchronous native x 10) x 80.25 ops/sec ±0.35% (74 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (synchronous js) x 2,117 ops/sec ±0.78% (84 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (synchronous js x 10) x 212 ops/sec ±0.69% (81 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (synchronous native) x 261 ops/sec ±0.46% (84 runs sampled)
RDF Dataset Normalization / #block-2 block-2 / (synchronous native x 10) x 25.97 ops/sec ±0.68% (63 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (asynchronous js) x 311 ops/sec ±0.97% (82 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (asynchronous js x 10) x 31.93 ops/sec ±0.94% (74 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (asynchronous native) x 66.57 ops/sec ±0.64% (76 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (asynchronous native x 10) x 21.43 ops/sec ±0.64% (53 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (synchronous js) x 472 ops/sec ±4.11% (82 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (synchronous js x 10) x 48.36 ops/sec ±0.96% (74 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (synchronous native) x 69.86 ops/sec ±0.40% (79 runs sampled)
RDF Dataset Normalization / #block-10 block-10 / (synchronous native x 10) x 6.98 ops/sec ±0.32% (37 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (asynchronous js) x 30.58 ops/sec ±4.19% (73 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (asynchronous js x 10) x 2.92 ops/sec ±4.14% (19 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (asynchronous native) x 7.58 ops/sec ±0.58% (40 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (asynchronous native x 10) x 2.34 ops/sec ±1.02% (16 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (synchronous js) x 49.03 ops/sec ±0.68% (75 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (synchronous js x 10) x 4.75 ops/sec ±1.85% (27 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (synchronous native) x 7.50 ops/sec ±0.68% (40 runs sampled)
RDF Dataset Normalization / #block-100 block-100 / (synchronous native x 10) x 0.74 ops/sec ±1.54% (8 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (asynchronous js) x 2.44 ops/sec ±5.87% (17 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (asynchronous js x 10) x 0.25 ops/sec ±2.35% (6 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (asynchronous native) x 0.76 ops/sec ±0.93% (8 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (asynchronous native x 10) x 0.24 ops/sec ±1.16% (6 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (synchronous js) x 3.59 ops/sec ±5.53% (22 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (synchronous js x 10) x 0.39 ops/sec ±1.40% (6 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (synchronous native) x 0.75 ops/sec ±1.40% (8 runs sampled)
RDF Dataset Normalization / #block-1000 block-1000 / (synchronous native x 10) x 0.07 ops/sec ±0.79% (5 runs sampled)
Done.

</pre>

![image](https://user-images.githubusercontent.com/39191/51066590-0008ed80-15c0-11e9-9e73-890ddc644e92.png)

</details>

👌 

-------

so..... success??

**Comment by dlongley** [comment]
@davidlehn, I'm +1 to publishing something without the native dependency at all and figuring out a way to add it in separately and manually. I suspect most people would prefer the JS only version and the current setup is just causing trouble; the native version is really for very specialized/specific use cases.

**Comment by paulirish** [comment]
I filed https://github.com/digitalbazaar/rdf-canonize/issues/14 to continue the conversation.

**Comment by patrickhulce** [comment]
Just noticed that rdf-canonize was published without the native dependency, hurray! 🎉 

Does this mean it will be arriving in `jsonld`'s updated deps very soon? 😃

**Comment by davidlehn** [comment]
@patrickhulce Should be fixed in 1.5.0.
