### ISSUE TITLE
Fix JSON-LD 1.1 @version processing

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld.js#275]
See: https://github.com/w3c/json-ld-syntax/issues/99

**Comment by davidlehn** [comment]
Is the current JSON-LD 1.1 test conformance enough to close this?

**Comment by gkellogg** [comment]
Yes, I think the current test coverage is adequate. Note that most tests still assert `@version`, or do so through options, but there are tests that look for it without options, or with the version option set explicitly to `json-ld-1.0`.
