### ISSUE TITLE
CDNJS CDN link broken

### ISSUE THREAD

**Issue by marcodarko** [digitalbazaar/jsonld.js#278]
resource is not loading 404

**Comment by davidlehn** [comment]
Yeah, I guess no one ever updated their system to work with newer file layouts or something.  I added a PR that might fix it:
https://github.com/cdnjs/cdnjs/pull/13140

**Comment by davidlehn** [comment]
Fixed now.  Newer version are available on cdnjs: https://cdnjs.com/libraries/jsonld
