### ISSUE TITLE
possible to get one resource instead of whole @graph?

### ISSUE THREAD

**Issue by lpsBetty** [digitalbazaar/jsonld.js#28]
i have an json-ld object with @graph: [...]

is it possible to easily get the 'right' object out of the array with the specific @uri defined? 

or do i need to get it manually like this:

<pre>
$.each(data["@graph"], function(index, resource) {
  if(resource["@id"] === uri) {
    return resource;
  }
});
</pre>

**Comment by dlongley** [comment]
This is now included in JSON-LD framing, you can pick out via an `@id`.
