### ISSUE TITLE
Correct way of converting multiple JSON files to single JSON file?

### ISSUE THREAD

**Issue by goldingdamien** [digitalbazaar/jsonld.js#281]
Is this library(including the cli) appropriate for merging multiple JSON file into one, and if so how could it be achieved?

For example(not correct JSON-LD syntax):
```
json1.json:
{
  "key1": "normal string",
  "key2": json2.json@key1"
  "key3": {
    "key4": json2.json@key2"
  }
}
json2.json:
{
  "key1": "name",
  "key2": "description"
}
outputs to:
{
  "key1": "normal string",
  "key2": "name"
  "key3": {
    "key4": "description"
  }
}
```

Regards.

**Comment by elf-pavlik** [comment]
I think you would just need JSON-LD context for your data. Then you can parse each json file providing that context to the parser. Next step could possibly serialize each result to n-triples and simply concatenate them. In the end you could parse those concatenated n-triples again and serialize it to JSON-LD using your context once again.

> `"key2": json2.json@key1"`

I don't understand this way of transclusion of values from one file in the other file. It seems to me like some custom convention used in your data and seems to assume that certain key will appear only once in that 'source' file. Most likely you will need to have a custom script to substitute all the values before moving to JSON-LD.

**Comment by goldingdamien** [comment]
Thank you for your answer.
I am actually not very familiar with JSON-LD so am not very familiar with a lot of the terminology.
I am trying to find out if JSON-LD is appropriate for my goal before investing more time in learning a lot of the details.
The transclusion notation I included was merely a concept and not actual syntax. I do not mind how that notation looks.
All I wish to do is merge JSON files(not specifically JSON-LD files) and it would seem JSON-LD being about linking should be able to do this, but it is not clear from the docs I have seen.
I would also like to know If it is possible but will result in additional data such as @context.
It would be best if the CLI of this repository could just do what I want, but if not then I will look into extending it.
Any information would be much appreciated. Regards.

**Comment by elf-pavlik** [comment]
> I am actually not very familiar with JSON-LD so am not very familiar with a lot of the terminology.

I strongly recommend checking out https://json-ld.org/learn.html which besides articles also links to nice animated introductory videos.

**Comment by goldingdamien** [comment]
@elf-pavlik Thank you. After looking at everything, I decided it was better to create my own library based on the $ref format in json schema:
https://github.com/goldingdamien/json-ref-merger
