### ISSUE TITLE
_setDefaults Syntax

### ISSUE THREAD

**Issue by kezike** [digitalbazaar/jsonld.js#282]
https://github.com/digitalbazaar/jsonld.js/blob/c8f945d4f0caeac02c178cc0cfab1816ef584281/lib/jsonld.js#L1048

When trying to include jsonld in webpack, I am discovering this seemingly incorrect syntax. For one, there seems to be an assignment within a JSON object in line 1049. Additionally, I am unclear of the propriety of the ellipsis before `defaults` in line 1050. Again, I am just a messenger of this webpack-generated error and I hope that we can resolve this soon.

**Comment by davidlehn** [comment]
See also https://github.com/digitalbazaar/jsonld.js/pull/279.

It's ES2018 Object spread syntax: https://github.com/tc39/proposal-object-rest-spread.  I'm unsure what we'll do about this issue.  If you're running webpack yourself you can use a babel plugin just like jsonld.js itself does: https://babeljs.io/docs/en/babel-plugin-transform-object-rest-spread.html. 
 See package.json for how it's used here.

**Comment by kezike** [comment]
Thanks a lot David! That makes a lot of sense. I was able to get around the webPack error after adding something similar to a rule in `jsonld`'s webPack.config. However, I have been coming across another error around `regeneratorRuntime` not being defined. I think this points to the underlying issue of how to properly incorporate `jsonld`'s webPack.config into another app's webPack.config so that everything is properly loaded and defined. Please let me know if this is a topic appropriate for a separate issue and where I should file that issue if so.

**Comment by kezike** [comment]
Check out `transform-runtime` here: https://babeljs.io/docs/en/babel-plugin-transform-runtime

**Comment by chigix** [comment]
A webpack friendly entry should be applied: https://github.com/digitalbazaar/jsonld.js/pull/317
