### ISSUE TITLE
jsonldjs is not defined in webpack output

### ISSUE THREAD

**Issue by kezike** [digitalbazaar/jsonld.js#283]
After configuring `transform-runtime`, updating `babel-core`, and doing a number of other things to configure my `webpack.config.js` file to accommodate `jsonld`, I am getting the following error: `jsonldjs is not defined`. I understand that Issue #92 referenced this issue and alluded that it was fixed, but alas, I am still running into the issue. Could anyone possible shed light on this. I am glad to share more details as needed.

**Comment by davidlehn** [comment]
That error is happening when you load the script or when you try to use "jsonldjs"?  Honestly, I forgot that "jsonldjs" code was even in the source anymore!  We've only been using "jsonld" for a long long time.  Maybe that's a "strict" mode issue?  A basic browser test with the distributed webpack built code shows that "jsonldjs" doesn't even exist so I'm not sure why it might be running at all for you.

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/jsonld@1.2.1/dist/jsonld.min.js"></script>
  <script>
    console.log('jsonldjs:', typeof jsonldjs);
    console.log('jsonld:', typeof jsonld);
  </script>
</head>
<body></body>
</html>
```

**Comment by kezike** [comment]
The error occurs when I load the script. I am actually not even loading the script from an html document as a CDN, but rather am loading it as an npm module from within a js script, which is included from another script, which is then included in an html document. At the moment, webpack seems to build fine, but when I visit any of my pages, I am getting the jsonld error. Here is how my webpack looks for reference:
`
const path = require('path');
module.exports = { 
    entry: './app/index.js',
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: 'app.bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                loader: 'style!css!'
            },
            {
                test: /node_modules\/jsonld/,
                loader: 'babel-loader',
                options: {
                    presets: ['env'],
                    plugins: [
                        ['transform-object-rest-spread', {useBuiltIns: true}],
                        ['@babel/plugin-transform-runtime'],
                    ]
                }
            },
            {
                test: /\.js?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['env'],
                    plugins: [
                        ['transform-object-rest-spread', {useBuiltIns: true}],
                        ['@babel/plugin-transform-modules-commonjs'],
                        ['@babel/plugin-transform-regenerator'],
                        ['@babel/plugin-transform-runtime']
                    ]
                }
            }
        ]
    }
}
`

**Comment by kezike** [comment]
BUMP

**Comment by dlongley** [comment]
@davidlehn, it seems to me that `jsonldjs` as a global has been unsupported for some time and is broken. Are you able to simply remove it to resolve this issue?

**Comment by kezike** [comment]
According to `grep`, `jsonldjs` appears in `jsonld/lib/jsonld.js` as well as in various `dist` files, such as `jsonld/dist/jsonld.js`, `jsonld/dist/jsonld.min.js`, and `jsonld/dist/node6/lib/jsonld.js`. However, after commenting out these references, I am still getting the error, `Uncaught ReferenceError: jsonldjs is not defined`. Is there another way to remove these `jsonldjs` references?

**Comment by davidlehn** [comment]
I attempted a fix via removing that old code and just using the CommonJS style.  It's tacked on the end of webpack and babel updates.  Let me know if it works.  It'll probably be released soon after some testing.
https://github.com/digitalbazaar/jsonld.js/pull/285
https://github.com/digitalbazaar/jsonld.js/pull/285/commits/bc73a416e0fa94ecf2944c6c23251e33c3e8f241

**Comment by davidlehn** [comment]
I just went ahead and released 1.4.0 with the changes.  `jsonldjs` is gone.  If other exciting new problems were introduced, please open a new issue.

**Comment by kezike** [comment]
The very strange thing is that after installing the `jsonld` v1.4.0, I am still getting the `jsonldjs` error from the browser. I have inspected the package myself and it appears to no longer be referenced as you say, so this is very strange that it still ends up in my app.bundle.js webpack output. I was thinking that maybe it is the result of some kind of caching behavior, but after some additional investigation, I am no longer convinced of this. Do you notice this behavior by any chance?

**Comment by kezike** [comment]
I wonder if this has anything to do with the fact that I am trying to use `jsonld-signatgures`, which has `jsonld` v^1.1.0 in its `package.json`. I'm not super convinced by this, but if so, it is unclear how/when this version of `jsonld` would have even been installed in the build process. Thoughts?

**Comment by davidlehn** [comment]
The `jsonldjs` symbol has to come from somewhere! ;-)  It's probably another package pulling in an older version.  But ^1.1.0 should pull in 1.4.0.  If you reinstall dependencies does it fix things?  Might also try searching the entire recursive dependencies directory for anywhere with that symbol.

**Comment by kezike** [comment]
Yep, was able to find that `rdflib` is somehow bringing it in when I load files with the pattern, `test: /node_modules\/jsonld/` in `webpack.config.js` file. I prevented this by adding a carat in front: `test: /^node_modules\/jsonld/`, which only loads `jsonld` and `jsonld-signatures`, as was my intention, without loading folders like `node_modules/rdflib/node_modules/jsonld`. This is a workaround, which does not address the fact that `rdflib` is somehow still pulling in this stale `jsonld` version, but that is beyond the scope of this comment. The only emergent issue that came from this fix is that `jsigs.use` is somehow not recognized when I call `jsigs.use('jsonld', jsonld);`. I have commented this out for now, but I may create a separate issue for this in the `jsonld-signatures` repo if it proves problematic. Thanks for your patience and help David!

**Comment by kezike** [comment]
UPDATE: From revisiting the `jsonld-signatures` repo, it appears that `jsigs.use` is no longer featured in the example. I suppose this is a deprecated function now.

**Comment by davidlehn** [comment]
That injector `use` pattern was causing more trouble than it solved.
