### ISSUE TITLE
Relative IRI not being handled in all cases

### ISSUE THREAD

**Issue by bradleypallen** [digitalbazaar/jsonld.js#29]
It appears that relative IRIs are not being expanded in cases where a @base IRI is  not supplied in an inline @context, or when the @context is supplied by reference.

Here is a terminal session where ./bin/jsonld format, and then ./bin/jsonld flatten are called on a JSON-LD document with absolute IRIs:

    $ curl -v -XGET 'http://localhost:8081/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7' | ./bin/jsonld format
    * About to connect() to localhost port 8081 (#0)
    *   Trying 127.0.0.1...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connected
    * Connected to localhost (127.0.0.1) port 8081 (#0)
    > GET /person/e0242b10-c174-11e2-8d4a-c9031da4b7f7 HTTP/1.1
    > User-Agent: curl/7.27.0
    > Host: localhost:8081
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Content-Type: application/json
    < Content-Length: 233
    < Date: Tue, 21 May 2013 22:41:20 GMT
    < Connection: keep-alive
    < 
    { [data not shown]
    100   233  100   233    0     0    910      0 --:--:-- --:--:-- --:--:--   920
    * Connection #0 to host localhost left intact
    * Closing connection #0
    {
      "@context": "http://localhost:8081/contexts/person",
      "image": "http://manu.sporny.org/images/manu.png",
      "@id": "http://localhost:8081/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7",
      "name": "Manu Sporny",
      "homepage": "http://manu.sporny.org/"
    }
    $ curl -v -XGET 'http://localhost:8081/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7' | ./bin/jsonld flatten
    * About to connect() to localhost port 8081 (#0)
    *   Trying 127.0.0.1...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connected
    * Connected to localhost (127.0.0.1) port 8081 (#0)
    > GET /person/e0242b10-c174-11e2-8d4a-c9031da4b7f7 HTTP/1.1
    > User-Agent: curl/7.27.0
    > Host: localhost:8081
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Content-Type: application/json
    < Content-Length: 233
    < Date: Tue, 21 May 2013 22:41:36 GMT
    < Connection: keep-alive
    < 
    { [data not shown]
    100   233  100   233    0     0   1263      0 --:--:-- --:--:-- --:--:--  1273
    * Connection #0 to host localhost left intact
    * Closing connection #0
    [
      {
        "@id": "http://localhost:8081/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7",
        "http://schema.org/image": [
          {
            "@id": "http://manu.sporny.org/images/manu.png"
          }
        ],
        "http://schema.org/name": [
          {
            "@value": "Manu Sporny"
          }
        ],
        "http://schema.org/url": [
          {
            "@id": "http://manu.sporny.org/"
          }
        ]
      },
      {
        "@id": "http://manu.sporny.org/"
      },
      {
        "@id": "http://manu.sporny.org/images/manu.png"
      }
    ]

In contrast, here is a terminal session where ./bin/jsonld format, and then ./bin/jsonld flatten are called on a JSON-LD document with relative IRIs:

    $ curl -v -XGET 'http://localhost:8081/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7' | ./bin/jsonld format
    * About to connect() to localhost port 8081 (#0)
    *   Trying 127.0.0.1...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connected
    * Connected to localhost (127.0.0.1) port 8081 (#0)
    > GET /person/e0242b10-c174-11e2-8d4a-c9031da4b7f7 HTTP/1.1
    > User-Agent: curl/7.27.0
    > Host: localhost:8081
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Content-Type: application/json
    < Content-Length: 191
    < Date: Tue, 21 May 2013 22:42:13 GMT
    < Connection: keep-alive
    < 
    { [data not shown]
    100   191  100   191    0     0    424      0 --:--:-- --:--:-- --:--:--   435
    * Connection #0 to host localhost left intact
    * Closing connection #0
    {
      "@context": "/contexts/person",
      "image": "http://manu.sporny.org/images/manu.png",
      "@id": "/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7",
      "name": "Manu Sporny",
      "homepage": "http://manu.sporny.org/"
    }
    $ curl -v -XGET 'http://localhost:8081/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7' | ./bin/jsonld flatten
    * About to connect() to localhost port 8081 (#0)
    *   Trying 127.0.0.1...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connected
    * Connected to localhost (127.0.0.1) port 8081 (#0)
    > GET /person/e0242b10-c174-11e2-8d4a-c9031da4b7f7 HTTP/1.1
    > User-Agent: curl/7.27.0
    > Host: localhost:8081
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Content-Type: application/json
    < Content-Length: 191
    < Date: Tue, 21 May 2013 22:42:16 GMT
    < Connection: keep-alive
    < 
    { [data not shown]
    100   191  100   191    0     0    610      0 --:--:-- --:--:-- --:--:--   618
    * Connection #0 to host localhost left intact
    * Closing connection #0
    jsonld.FlattenError: Could not expand input before flattening.

Now if we make the referenced @context IRI absolute, then ./bin/jsonld flatten works correctly, but a call to ./bin/jsonld normalize does not:

    $ cat manu-id-relative.jsonld | ./bin/jsonld format
    {
      "@context": "http://localhost:8081/contexts/person",
      "image": "http://manu.sporny.org/images/manu.png",
      "@id": "/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7",
      "name": "Manu Sporny",
      "homepage": "http://manu.sporny.org/"
    }
    $ cat manu-id-relative.jsonld | ./bin/jsonld flatten
    [
      {
        "@id": "/person/e0242b10-c174-11e2-8d4a-c9031da4b7f7",
        "http://schema.org/image": [
          {
            "@id": "http://manu.sporny.org/images/manu.png"
          }
        ],
        "http://schema.org/name": [
          {
            "@value": "Manu Sporny"
          }
        ],
        "http://schema.org/url": [
          {
            "@id": "http://manu.sporny.org/"
          }
        ]
      },
      {
        "@id": "http://manu.sporny.org/"
      },
      {
        "@id": "http://manu.sporny.org/images/manu.png"
      }
    ]    $ cat manu-id-relative.jsonld | ./bin/jsonld normalize
    
    /Users/ballen/github/local/jsonld-test/jsonld.js/js/jsonld.js:5429
          throw new JsonLdError(
                ^
    jsonld.ParseError: Error while parsing N-Quads; invalid quad.
        at _parseNQuads (/Users/ballen/github/local/jsonld-test/jsonld.js/js/jsonld.js:5429:13)
        at createArray (/Users/ballen/github/local/jsonld-test/jsonld.js/js/jsonld.js:2458:20)
        at processGroup (/Users/ballen/github/local/jsonld-test/jsonld.js/js/jsonld.js:2375:16)
        at nameDuplicates (/Users/ballen/github/local/jsonld-test/jsonld.js/js/jsonld.js:2371:5)
        at nameBlankNodes (/Users/ballen/github/local/jsonld-test/jsonld.js/js/jsonld.js:2361:7)
        at hashUnnamed (/Users/ballen/github/local/jsonld-test/jsonld.js/js/jsonld.js:2317:16)
        at Object._onImmediate (/Users/ballen/github/local/jsonld-test/jsonld.js/js/jsonld.js:2313:37)
        at processImmediate [as _immediateCallback] (timers.js:309:15)

If the above example is changed so that the @context is supplied in-line with a @base IRI, then both flatten and normalize work correctly. If the @context is supplied in-line without a @base IRI, then normalize fails as shown above.

I believe this behavior is inconsistent with the statement "JSON-LD allows IRIs to be specified in a relative form which is resolved against the document base according section 5.1 Establishing a Base URI of [RFC3986].", in section 6.1 of the latest JSON-LD specification, since it should be possible to follow the guidance in sections 5.12 or 5.1.3 of RFC3986 to establish a base IRI.

**Comment by dlongley** [comment]
This issue needs to be addressed in [jsonld-cli](https://github.com/digitalbazaar/jsonld-cli) now.
