### ISSUE TITLE
Have activeContext.sealed use a Set rather than a hashmap

### ISSUE THREAD

**Issue by cwebber** [digitalbazaar/jsonld.js#290]
Assuming #289 is pulled in, activeContext.sealed should use a Set.  Currently it's using the "hashmap as a set" hack because of cache serialization issues.  Ie, shenanigans like so would happen:

`Set { '[', 'o', 'b', 'j', 'e', 'c', 't', ' ', 'S', ']' }`

**Comment by dlongley** [comment]
This is not part of the implementation, closing.
