### ISSUE TITLE
Framing does not respect specified value

### ISSUE THREAD

**Issue by angelo-v** [digitalbazaar/jsonld.js#300]
**Expected Behaviour**: Given a document with 2 persons "Jane" and "John" and a frame for `"givenName": "John"` I expect the result to contain only John, but not Jane.

**Actual Behaviour**: The result contains both persons, just that Janes givenName is set to `null`

I have set up the [exact scenario in the playground here](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40vocab%22%3A%22https%3A%2F%2Fschema.org%2F%22%7D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%221%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22John%20Doe%22%2C%22givenName%22%3A%22John%22%2C%22familyName%22%3A%22Doe%22%7D%2C%7B%22%40id%22%3A%222%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22Jane%20Doe%22%2C%22givenName%22%3A%22Jane%22%7D%5D%7D&frame=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40vocab%22%3A%22https%3A%2F%2Fschema.org%2F%22%7D%2C%22givenName%22%3A%22John%22%7D).

The expected result there would be:

```
{
  "@context": {
    "@version": 1.1,
    "@vocab": "https://schema.org/"
  },
  "@id": "1",
  "@type": "Person",
  "name": "John Doe",
  "givenName": "John",
  "familyName": "Doe"
}
```

**Affected versions**
- jsonld playground as  of 2019-03-04
- jsonld npm package version 1.5.4
- works *as expected* in the [RDF Distiller](http://rdf.greggkellogg.net/distiller?command=serialize)

**Comment by davidlehn** [comment]
I'm not sure if matching on literal values is in the spec.  See the note here for instance: https://w3c.github.io/json-ld-framing/#default-content.  I don't recall historical reason why that is one way or another.

@gkellogg Is the Ruby code doing literal matching?  I don't think we have spec text or tests for this?

**Comment by gkellogg** [comment]
It's allowed for in [Value Pattern Matching](https://www.w3.org/TR/json-ld11-framing/#value-matching).

> _Value_ matches _pattern_ when _pattern_ is `wildcard` or _v1_ is in _v2_, ...

**Comment by davidlehn** [comment]
Huh, there's even a whole section on it.  Maybe I should re-read the newer spec text!  I suppose this is a bug then.  Looks like maybe the value pattern tests that say "others are filtered" may not be testing that filtering part?
