### ISSUE TITLE
Context link in HTTP Header not yet implemented?

### ISSUE THREAD

**Issue by digikim** [digitalbazaar/jsonld.js#31]
Hello,

While trying to use jsonld.js to parse JSON-LD data, I noticed that jsonld.js does not currently support defining the link to the context file in the HTTP Header (cf. http://www.w3.org/TR/json-ld/#interpreting-json-as-json-ld ). I also browsed the source code and the test cases, and I don't think there is an implementation.

Did I miss something or is the HTTP Header context link implementation not yet implemented? Thanks in advance!

**Comment by dlongley** [comment]
This issue needs to be addressed in [jsonld-cli](https://github.com/digitalbazaar/jsonld-cli) now.
