### ISSUE TITLE
Deserialize from rdflib

### ISSUE THREAD

**Issue by linonetwo** [digitalbazaar/jsonld.js#314]
I've tried 

```js
const CONTAINER = $rdf.sym(containerUrl); // in case a bare URI was passed
        const containerStore = $rdf.graph();
        await new $rdf.Fetcher(containerStore).load(CONTAINER);

        // Obtain the list of RDF documents
        const CONTAINS = $rdf.sym('http://www.w3.org/ns/ldp#contains');
        const documents = containerStore
          .each(CONTAINER, CONTAINS)
          .filter(document => /\.(?:ttl|nt|n3|jsonld)$/.test(document.value));

        // Fetch all RDF documents and return their union
        const union = $rdf.graph();
        await new $rdf.Fetcher(union).load(documents);
        console.log('union', union);
        
        const doc = await jsonld.fromRDF(union, {format: 'application/n-quads'});
        console.log('doc', doc);
```

But the error is `TypeError: input.split is not a function`

**Comment by RubenVerborgh** [comment]
> ```js
> const doc = await jsonld.fromRDF(union, {format: 'application/n-quads'});
> ```

This seems questionable, given that `union` is an RDF store and not an N-Quads document.

**Comment by elf-pavlik** [comment]
I think one should be able to do it with RDFJS Sink interface http://rdf.js.org/stream-spec/#sink-interface
`union` should provide [RDFJS Source](http://rdf.js.org/stream-spec/#source-interface) and JSON-LD serializer should provide RDFJS Sink. This way one could do something like `jsonldSerializer.import(union.match())` and get `Stream<string>` with resulting JSON-LD document.
