### ISSUE TITLE
'.jsonld' is removed from '@id' uri string value when expand/flatten

### ISSUE THREAD

**Issue by zaliqarosli** [digitalbazaar/jsonld.js#322]
When using both jsonld.expand and jsonld.flatten methods, the returned expanded jsonld has the `.jsonld` extension knocked off its unique `@id` URI, preventing me from linking/pointing to the correct URI

**Comment by davidlehn** [comment]
Can you provide a short example code snippet?

**Comment by zaliqarosli** [comment]
<img width="486" alt="Screenshot 2019-07-25 16 20 07" src="https://user-images.githubusercontent.com/17415878/61905919-3b359300-aef8-11e9-9fd5-d59b0d060f8e.png">

so for example, when I jsonld.expand("https://raw.githubusercontent.com/ReproNim/schema-standardization/master/activities/MedicalHistory-LORIS/medicalhistory_page1.jsonld"), the returned doc has as '@id' the same URI but without '.jsonld' extension.

<img width="400" alt="Screenshot 2019-07-25 16 22 25" src="https://user-images.githubusercontent.com/17415878/61906061-8485e280-aef8-11e9-9d9c-b5e5f14cbbad.png">

to clarify, i have not manipulated the value of '@id' in any way

**Comment by davidlehn** [comment]
Your simplified data is:
```jsonld
{
    "@context": [ "https://raw.githubusercontent.com/ReproNim/schema-standardization/master/contexts/generic.jsonld",
        "https://raw.githubusercontent.com/ReproNim/schema-standardization/master/activities/MedicalHistory-LORIS/medicalhistory_context.jsonld"
    ],
    "@type": "https://raw.githubusercontent.com/ReproNim/schema-standardization/master/schemas/Activity.jsonld",
    "@id": "medicalhistory_page1"
}
```
You are using a relative `@id`.  You then process it like this:
```js
jsonld.expand("https://raw.githubusercontent.com/ReproNim/schema-standardization/master/activities/MedicalHistory-LORIS/medicalhistory_page1.jsonld");
```
The expanded result will use the id relative to the document URL, which would be `https://raw.githubusercontent.com/ReproNim/schema-standardization/master/activities/MedicalHistory-LORIS/` + `medicalhistory_page1`.  You just happen to have the same id and URL ending path component.  The whole `medicalhistory_page1.jsonld` part was removed when doing the relative URL processing.

Similarly, if you process this on the json-ld.org playground, you would get an id relative to the playground URL:
```jsonld
[
  {
    "@id": "https://json-ld.org/playground/medicalhistory_page1",
    "@type": [
      "https://raw.githubusercontent.com/ReproNim/schema-standardization/master/schemas/Activity.jsonld"
    ]
  }
]
```
I'm not sure what you expect the output to be here.  Also, the `@type` URL is literally a `Activity.jsonld` resource.  That's probably not what you mean to do?

**Comment by zaliqarosli** [comment]
@davidlehn thanks for looking into this. would having the following in one of the contexts (https://raw.githubusercontent.com/ReproNim/schema-standardization/master/activities/MedicalHistory-LORIS/medicalhistory_context.jsonld) not resolve the relative `@id` to its proper one:

```
        "medicalhistory_page1": {
            "@id": "https://raw.githubusercontent.com/ReproNim/schema-standardization/master/activities/MedicalHistory-LORIS/medicalhistory_page1.jsonld",
            "@type": "@id"
        },
``` ?

If not, then I believe this is a problem with my jsonld and you can close this issue
