### ISSUE TITLE
Subframes with default values are not causing matches

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld.js#323]
See: https://github.com/w3c/json-ld-syntax/issues/19

I think that this is just a bug in the jsonld.js implementation, the `matchesSome` flag is not set to true when a default is set in the subframe but the key (`states` in that issue) is not present in the data.

Adding `matchesSome = true` before continuing here would fix it:
https://github.com/digitalbazaar/jsonld.js/blob/master/lib/frame.js#L471

Possible duplicate of #155.

**Comment by gkellogg** [comment]
I think this was for https://github.com/w3c/json-ld-framing/issues/58.

**Comment by dlongley** [comment]
My understanding is that this has been fixed, closing. If not fixed, please reopen.
