### ISSUE TITLE
Remove support for legacy callback APIs

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld.js#330]
We should make a breaking change and remove support for the callback versions of the API, supporting only the promise version.

This also includes removing support for the callback version of document loader and the complicated normalization functions we have around making that work. This may need to be done sooner rather than later to support JSON-LD 1.1 requirements with the `options` param for document loaders.

**Comment by davidlehn** [comment]
- +1.
- I was thinking removing callbacks and switching to ES modules should happen in the same big break.
- ES module change gets a bit tricky with the top level wrapper style used here.  I was unsure what the new design should be for that, if any.  Maybe that can just be dropped?
- A thought was to use regular exports for the main API, and have some new way to wrap it all if that's still needed.  Maybe wrapper API would handle defaults like a default document loader?  The same wrapping style could probably be used to provide a callbackify wrapping of the API, if that's desired.
- Whatever the new API is, we'd like to make sure it works well with ES module tree shaking tools.

**Comment by dlongley** [comment]
Closing as a duplicate of #399.
