### ISSUE TITLE
IE11 syntax error

### ISSUE THREAD

**Issue by flyon** [digitalbazaar/jsonld.js#331]
I'm including `node_modules/jsonld/dist/jsonld.js` in my bundle. It's working on all modern browsers but IE11 gives a syntax error, preventing the bundle from being loaded.

here's the bit of the bundle it fails at, which comes straight from ` node_modules/jsonld/dist/jsonld.js` .. the syntax error happens at eval:

```
/***/ "./node_modules/canonicalize/lib/canonicalize.js":
/*!*******************************************************!*\
  !*** ./node_modules/canonicalize/lib/canonicalize.js ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
eval("/* jshint esversion: 6 */\n/* jslint node: true */\n\n\nmodule.exports = function (object) {\n  return serialize(object);\n\n  function serialize (object) {\n    if (object === null || typeof object !== 'object' || object.toJSON != null) {\n      return JSON.stringify(object);\n    }\n    if (Array.isArray(object) && object.length === 0) {\n      return '[]';\n    }\n    if (Array.isArray(object) && object.length === 1) {\n      return '[' + serialize(object[0]) + ']';\n    }\n    if (Array.isArray(object)) {\n      return '[' + object.reduce((t, cv, ci) => {\n        t = (ci === 1 ? serialize(t) : t);\n        return t + ',' + serialize(cv);\n      }) + ']';\n    }\n    const keys = Object.keys(object);\n    if (keys.length === 0) {\n      return '{}';\n    }\n    if (keys.length === 1) {\n      return '{' + serialize(keys[0]) + ':' + serialize(object[keys[0]]) + '}';\n    }\n    return '{' + keys.sort().reduce((t, cv, ci) => {\n      t = (ci === 1 ? serialize(t) + ':' + serialize(object[t]) : t);\n      return t + ',' + serialize(cv) + ':' + serialize(object[cv]);\n    }) + '}';\n  }\n};\n\n\n//# sourceURL=webpack://%5Bname%5D/./node_modules/canonicalize/lib/canonicalize.js?");

/***/ }),
```

**Comment by davidlehn** [comment]
If you have time to track this down, there's not much code there, and I don't think it's doing anything complex that would be an IE11 issue.  I'm pretty sure we've bundled this up into something that has worked in IE11, but I'm not sure.

Source is from here:
https://github.com/erdtman/canonicalize/blob/master/lib/canonicalize.js

Maybe there's a babel or webpack bug.  Perhaps try building jsonld with latest tools and see if that fixes it?  Fallback to pinpoint the problem by removing code from that string until it works.

**Comment by flyon** [comment]
@davidlehn right I tracked it down now... that file uses ES6 arrow functions `=>` which causes a syntax error in IE11. 

it also sais `/* jshint esversion: 6 */` on the top, so thats not suprising.

So I don't think this should be in the bundle that is made to be used in all browsers.

**Comment by davidlehn** [comment]
Babel wasn't running on that recently added `canonicalize` lib. Fixed in 1.8.1. Try it out.

**Comment by flyon** [comment]
yes no more syntax error now! tnx

**Comment by flyon** [comment]
just upgraded from `1.8.1` and now I'm getting the same error again in `3.3.0` . Exectly the same problem. Arrow functions in `node_modules/jsonld/dist/jsonld.min.js`

**Comment by davidlehn** [comment]
Fixed in 3.3.1.  The newly added `lru-cache` dependency wasn't run through babel.

I'm not sure how to easily test for these issues.  The tooling and defaults are moving away from supporting such old browsers.

**Comment by flyon** [comment]
yeah understandably, but I think its good to keep supporting pure ES5 for now, without any ES6 features. So this is great. Kudo's for the quick fix 🙌

**Comment by flyon** [comment]
sorry, there is still more ES6 in the bundles. Next error that shows up is about `function*` 
from this code
```
/***/ "./node_modules/yallist/iterator.js":
/*!******************************************!*\
  !*** ./node_modules/yallist/iterator.js ***!
  \******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
eval("\nmodule.exports = function (Yallist) {\n  Yallist.prototype[Symbol.iterator] = function* () {\n    for (let walker = this.head; walker; walker = walker.next) {\n      yield walker.value\n    }\n  }\n}\n\n\n//# sourceURL=webpack://%5Bname%5D/./node_modules/yallist/iterator.js?");
```

and I also see quite a few `Symbol.iterator` occurrences, which are ES6

**Comment by davidlehn** [comment]
@flyon Try 3.3.2.  lru-cache pulled in yallist with generator functions.  I think the Symbol.iterators were already polyfilled.
