### ISSUE TITLE
Do not process `@context` in JSON literals

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld.js#339]
We currently process `@context` anywhere it appears in a document in a pre-processing step. This breaks JSON literals. I'm working on a patch to do JIT context processing instead -- with a number of other caching improvements. This patch should also fix this bug.

**Comment by davidlehn** [comment]
Is a main test suite test needed for variations of this or is that too specific of an implementation detail of what not to do?
cc: @gkellogg

**Comment by gkellogg** [comment]
I think anytime an implementation encounters an issue that might not be covered by the test suite and others might make it, it is appropriate to add such a test to the suite. 

If you’d like to contribute such a test, that would be great.

**Comment by dlongley** [comment]
Addressed by #342.
