### ISSUE TITLE
Blank node names getting lost

### ISSUE THREAD

**Issue by hsolbrig** [digitalbazaar/jsonld.js#353]
The blank node in  http://tinyurl.com/vx4s9pd

Is not getting rendered.  Should it be?

**Comment by gkellogg** [comment]
In this case, "_:LT" is a blank node property, which is _not_ RDF, and it's output is controlled using an option [produceGeneralizedRdf](https://w3c.github.io/json-ld-api/#dom-jsonldoptions-producegeneralizedrdf), which may not be set by default, as it results in invalid N-Quads.

**Comment by hsolbrig** [comment]
Makes sense.  Had forgotten that this was a property - thanks.
