### ISSUE TITLE
frame.js state.graphStack is not used.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/jsonld.js#371]
`lib/frame.js` tracks graphs with `state.graphStack` but it doesn't look like they are used.

@gkellogg Was there a plan for this?  Pending tests that would need it?  Maybe something that didn't make it over from ruby?

It might be a good point for a debugging hook.

**Comment by gkellogg** [comment]
Perhaps we should add tests that would flesh out the need for this.

Intuitively, if pushing onto a shared stack when processing a named graph, you would need to revert to the previous state after processing, but a test that could fail would be useful. Or, if we can't come up with one, perhaps it's not really necessary after all.

**Comment by gkellogg** [comment]
See https://github.com/w3c/json-ld-framing/pull/97, I now believe `graphStack` serves no purpose.

**Comment by davidlehn** [comment]
Closed in https://github.com/digitalbazaar/jsonld.js/pull/377.
