### ISSUE TITLE
Make package.json be JSON-LD

### ISSUE THREAD

**Issue by cmungall** [digitalbazaar/jsonld.js#39]
On the eat-your-own-dogfoot principle, shouldn't
https://github.com/digitalbazaar/jsonld.js/blob/master/package.json

Have a context tag added?

Feel free to close this item without resolution as out of scope. But I thought it would make a nice example. And I need to generate some rdf from package.jsons for another project it would be good to have a standard context here.

**Comment by kevinSuttle** [comment]
See also: 
https://github.com/npm/npm/issues/4482#issuecomment-162135803 
https://github.com/npm/npm/issues/10859
https://github.com/npm/npm/issues/10832

**Comment by elf-pavlik** [comment]
http://linkedsoftwaredependencies.org/bundles/npm/jsonld

https://linkedsoftwaredependencies.org/
> Read why semantic software configurations improve experiment reproducibility
Access 475,000+ npm JavaScript libraries as 150,000,000+ RDF triples using TPF, HDT or Turtle
Perform queries over software modules
Instantiate software with Components.js, a semantic dependency injection framework
Find our source code on GitHub

It looks like @rubensworks works on it

**Comment by rubensworks** [comment]
Indeed, we ( @joachimvh, @RubenVerborgh and myself) are working on this.

Note that our mapped JSON-LD does not exactly correspond to the structure of the original package.json, because some parts are not directly convertable. @joachimvh did most of the work on this part, so he can provide further details on this.

**Comment by joachimvh** [comment]
One of the problems we had with only attaching a context file to the package.json was that many package.json files contained custom tags added by the creators which could cause conflicts. E.g. if 2 tags were mapped to `@id` and both of them occurred in the root.

Another reason we did some rewrites was to increase the number of URIs generated. E.g., the author field is just a string (or an object with name/e-mail). For those we tried to generate consistent unique URIs so an author of multiple packages could easily be linked between those packages.

**Comment by elf-pavlik** [comment]
Looking at: http://linkedsoftwaredependencies.org/bundles/npm/jsonld
```json
{
  "@context": [
    "https://linkedsoftwaredependencies.org/contexts/npm.jsonld"
  ],
  "@graph": [
    {
      "_id": "jsonld",
      "name": "jsonld",
      "description": "A JSON-LD Processor and API implementation in JavaScript.",
      "versions": {
        "0.0.1": "https://linkedsoftwaredependencies.org/bundles/npm/jsonld/0.0.1",
        ...
        "0.5.13": "https://linkedsoftwaredependencies.org/bundles/npm/jsonld/0.5.13"
      },
      "readme": "https://linkedsoftwaredependencies.org/bundles/npm/jsonld/README",
      "maintainers": [
        {
          "email": "mailto:dil@lehn.org",
          "@id": "https://linkedsoftwaredependencies.org/users/npm/davidlehn"
        },
        {
          "email": "mailto:dlongley@digitalbazaar.com",
          "@id": "https://linkedsoftwaredependencies.org/users/npm/dlongley",
          "foaf:name": "Dave Longley"
        },
        {
          "email": "mailto:mcollier@digitalbazaar.com",
          "@id": "https://linkedsoftwaredependencies.org/users/npm/mattcollier"
        },
        {
          "email": "mailto:msporny@digitalbazaar.com",
          "@id": "https://linkedsoftwaredependencies.org/users/npm/msporny"
        }
      ],
      "author": {
        "email": "mailto:support@digitalbazaar.com",
        "@id": "mailto:support@digitalbazaar.com",
        "foaf:name": "Digital Bazaar, Inc.",
        "foaf:homepage": "http://digitalbazaar.com/"
      },
      "repository": {
        "@id": "git+ssh://git@github.com/digitalbazaar/jsonld.js.git",
        "@type": "doap:GitRepository"
      },
      "homepage": "http://github.com/digitalbazaar/jsonld.js",
      "keywords": [
        "JSON",
        "Linked Data",
        "JSON-LD",
        "RDF",
        "Semantic Web",
        "jsonld"
      ],
      "contributors": [
        {
          "email": "mailto:dlongley@digitalbazaar.com",
          "@id": "https://linkedsoftwaredependencies.org/users/npm/dlongley",
          "foaf:name": "Dave Longley"
        }
      ],
      "bugs": {
        "url": "https://github.com/digitalbazaar/jsonld.js/issues",
        "email": "support@digitalbazaar.com"
      },
      "license": {
        "@id": "https://spdx.org/licenses/BSD-3-Clause.html",
        "spdx:name": "BSD-3-Clause"
      },
      "@id": "https://linkedsoftwaredependencies.org/bundles/npm/jsonld",
      "dcterms:license": {
        "@id": "https://spdx.org/licenses/BSD-3-Clause.html",
        "rdfs:label": "BSD-3-Clause"
      },
      "owl:sameAs": "https://www.npmjs.com/package/jsonld",
      "@type": "doap:Project",
      "created": "2012-09-05T17:11:42.229Z",
      "modified": "2017-10-05T21:47:15.029Z"
    },
    {
      "@id": "https://linkedsoftwaredependencies.org/bundles/npm/jsonld/0.4.12",
      "npm:dist-tag": "latest"
    },
    {
      "@id": "https://linkedsoftwaredependencies.org/bundles/npm/jsonld/0.5.13",
      "npm:dist-tag": "dev"
    }
  ]
}
```

With `@graph` removed (leaving out those two 'dist-tag') and context adjusted package.json could stay both:
* valid https://docs.npmjs.com/files/package.json
* valid JSON-LD

**Comment by kevinSuttle** [comment]
Nice. This is very similar to the GitHub API (v4) https://developer.github.com/v4/reference/object/repository/

**Comment by dlongley** [comment]
Closing as not actionable here -- an interesting idea but no need to be a long standing open issue in this repo.
