### ISSUE TITLE
Please upgrade to webcomponents

### ISSUE THREAD

**Issue by busynest** [digitalbazaar/jsonld.js#475]
I don't understand the reqire() stuff. Webcomponents are the future.

**Comment by aljones15** [comment]
https://developer.mozilla.org/en-US/docs/Web/Web_Components

> Web Components is a suite of different technologies allowing you to create reusable custom elements — with their functionality encapsulated away from the rest of your code — and utilize them in your web apps.

1. Web Components appears to be a front end only technology (this library is cross environment and must be usable in node)
2. Web Components appear to be highly based around associating javascript and css with an html element.

Can you possibly explain further what benefits would come from using web components with this library? Web Components appears to be a standard that developers of front end frameworks such as [Hyperapp](https://github.com/JorgeBucaran/hyperapp) or [Vue](https://vuejs.org/) can use to standardize the logic of associating code with HTML.

**Comment by busynest** [comment]
I use nodeJS too. I use https//www.lit.dev Web components standards seem to line up with nodeJS for future. I think benefits for you would be bundling and api. For the internet of hard to document web components, seems like a good fit. If i could already use your mom with lit and then bundle, then I must learn

**Comment by busynest** [comment]
Yes, Module Syntax. The import statement from the example in the documentation can't find the package.  I tried re-install, and re-start, nothing worked. I guess something to do with loaders and bare module resolution. Using lit-HTML. is just a library of sortcuts for Autonomous Custom HTML Elements.
