### ISSUE TITLE
ky-universal

### ISSUE THREAD

**Issue by johnwen84** [digitalbazaar/jsonld.js#482]
Hi @davidlehn 
I created an issue in the http-client repo about using the vulnerable ky-univeral package, which you kindly resolved. I tested it with our WhitSource scan and confirmed that the issue was gone. Now I'm wondering if jsonld will be updated soon to use the latest http-client (3.0.0)?
Thanks

**Comment by nikolaswise** [comment]
Seconding this – along with the update to ky-universal this version of http-client removes esm.js, allowing json-ld.js to run in serverless lambdas. Would love to see this version bumped.

**Comment by davidlehn** [comment]
v6.0.0 released with `@digitalbazaar/http-client` v3.2.0.

**Comment by danbri** [comment]
nearby: https://github.com/digitalbazaar/http-client/issues/18

/cc @ericprud
