### ISSUE TITLE
Different representation between @set and @list

### ISSUE THREAD

**Issue by MarcusElevait** [digitalbazaar/jsonld.js#514]
We have a simple turtle string:
```
ex:PersonShape sh:ignoredProperties ( rdf:type ) .
```

and the related context
```
'@id': 'http://www.w3.org/ns/shacl#ignoredProperties',
'@type': '@id',
'@container': '@set',
```

as the order of the ignored properties is not relevant, we want to use a set here.
However, after compacting it, we get the following:

![image](https://user-images.githubusercontent.com/95350049/226980823-d428f6ac-147a-4a79-a4bf-92a91aef3f03.png)

Whereas when we change the @container to @list  we get the correct representation:

![image](https://user-images.githubusercontent.com/95350049/226981047-3fec9b99-3cae-43dc-8102-5bb7ce6fc6ef.png)

I thought that both, @set and @list should be a simple json array after compacting. Is this intentional?

**Comment by davidlehn** [comment]
Can you provide minimal sample input and context?  Easiest way to debug this is to just put that in the playground and fiddle until it works.

**Comment by MarcusElevait** [comment]
Okay so here are the three quads, that are the input for this list:
```json
{
    "termType": "Quad",
    "subject": {
      "termType": "BlankNode",
      "value": "_:n3-4"
    },
    "predicate": {
      "termType": "NamedNode",
      "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first"
    },
    "object": {
      "termType": "NamedNode",
      "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
    },
    "graph": {
      "termType": "DefaultGraph",
      "value": ""
    }
  },
  {
    "termType": "Quad",
    "subject": {
      "termType": "BlankNode",
      "value": "_:n3-4"
    },
    "predicate": {
      "termType": "NamedNode",
      "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest"
    },
    "object": {
      "termType": "NamedNode",
      "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"
    },
    "graph": {
      "termType": "DefaultGraph",
      "value": ""
    }
  },
  {
    "termType": "Quad",
    "subject": {
      "termType": "NamedNode",
      "value": "http://example.com/ns#PersonShape"
    },
    "predicate": {
      "termType": "NamedNode",
      "value": "http://www.w3.org/ns/shacl#ignoredProperties"
    },
    "object": {
      "termType": "BlankNode",
      "value": "_:n3-4"
    },
    "graph": {
      "termType": "DefaultGraph",
      "value": ""
    }
  }
```

and the context is this (as i wrote in my original post):
```json
{
    '@id': 'http://www.w3.org/ns/shacl#ignoredProperties',
    '@type': '@id',
    '@container': '@set',
}
```

**Comment by MarcusElevait** [comment]
Sorry this was my bad, i was confused by the concept of sets and lists in shacl. so i will close this here.
