### ISSUE TITLE
Bug: Missing properties in compact and expand

### ISSUE THREAD

**Issue by jeremiahlee** [digitalbazaar/jsonld.js#529]
Properties seem to be removed from the output of `compact` and `expand` unexpectedly. The behavior of the playground and the library differs.

Using the example from the README:

```js
const context = {
  "name": "http://schema.org/name",
  "homepage": {"@id": "http://schema.org/url", "@type": "@id"},
  "image": {"@id": "http://schema.org/image", "@type": "@id"}
};

const doc = {
  "http://schema.org/name": "Manu Sporny",
  "http://schema.org/url": {"@id": "http://manu.sporny.org/"},
  "http://schema.org/image": {"@id": "http://manu.sporny.org/images/manu.png"}
};
```

If I rename the document property `"http://schema.org/name"` to `"name"` so that the full input is:

```json
{
  "@context": {
    "name": "http://schema.org/name",
    "homepage": {"@id": "http://schema.org/url", "@type": "@id"},
    "image": {"@id": "http://schema.org/image", "@type": "@id"}
  },
  "name": "Manu Sporny",
  "http://schema.org/url": {"@id": "http://manu.sporny.org/"},
  "http://schema.org/image": {"@id": "http://manu.sporny.org/images/manu.png"}
}
```

The _expanded_ and _compacted_ output [on the Playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22name%22%3A%22http%3A%2F%2Fschema.org%2Fname%22%2C%22homepage%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fschema.org%2Furl%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22image%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fschema.org%2Fimage%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22name%22%3A%22Manu%20Sporny%22%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fmanu.sporny.org%2F%22%7D%2C%22http%3A%2F%2Fschema.org%2Fimage%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fmanu.sporny.org%2Fimages%2Fmanu.png%22%7D%7D&context=%7B%7D) are the same if the document property is named `"name"` or `"http://schema.org/name"`. This is the behavior I would expect and consider correct.

However, using node v18.17.1 and jsonld v8.2.0 of the library produces different output. The `name` property will be missing on output.

```js
const jsonld = require("jsonld");

const context = {
	"name": "http://schema.org/name",
	"homepage": { "@id": "http://schema.org/url", "@type": "@id" },
	"image": { "@id": "http://schema.org/image", "@type": "@id" }
};
const doc = {
	"name": "Manu Sporny",
	"http://schema.org/url": { "@id": "http://manu.sporny.org/" },
	"http://schema.org/image": { "@id": "http://manu.sporny.org/images/manu.png" }
};

async function test() {
	const compacted = await jsonld.compact(doc, context);

	const expanded = await jsonld.expand(compacted);

	console.dir(compacted, { depth: null });
	console.dir(expanded, { depth: null });
}

test();
```

The console logs a compacted and expanded form with no `name` property.

```js
{
  '@context': {
    name: 'http://schema.org/name',
    homepage: { '@id': 'http://schema.org/url', '@type': '@id' },
    image: { '@id': 'http://schema.org/image', '@type': '@id' }
  },
  image: 'http://manu.sporny.org/images/manu.png',
  homepage: 'http://manu.sporny.org/'
}
```
```js
[
  {
    'http://schema.org/url': [ { '@id': 'http://manu.sporny.org/' } ],
    'http://schema.org/image': [ { '@id': 'http://manu.sporny.org/images/manu.png' } ]
  }
]
```

Is there a configuration difference between the Playground and the library? Am I incorrect in expecting the document properties to matched against the property names in the context?

**Comment by dlongley** [comment]
@jeremiahlee,

In your node + jsonld test case your input is different from the playground: it does not include `@context` in `doc`. This is why you see a difference and why `name` is dropped. There's no `@context` on the input `doc`, so `name` has no global mapping. The default behavior is to drop `name` when that happens. If you'd prefer to get an error instead, you can enable "safe mode" that will throw if anything gets dropped by passing `{safe: true}` as an option to functions like `compact()`.

**Comment by jeremiahlee** [comment]
@dlongley Thanks, I can confirm that adding the `@context` back to the document and sending an empty object `{}` as the second parameter to `jsonld.compact()` works as expected.

I thought it was quite strange to have to separate out the `@context` object from the doc to send to the `compact`, but the README example implied that to be the case because there is no `@context` on the document.

**Comment by jeremiahlee** [comment]
Working as designed
