### ISSUE TITLE
fromRDF generates verbose JSON-LD

### ISSUE THREAD

**Issue by RubenVerborgh** [digitalbazaar/jsonld.js#54]
The `fromRDF` method generates quite verbose JSON-LD.
For instance, take the following fragment:

``` JavaScript
var triples = { '@default': [
  {
    'subject':   { value: 'MyCollection', type: 'blank node' },
    'predicate': { value: 'hasCount', type: 'blank node' },
    'object':    { value: '16', datatype: 'http://www.w3.org/2001/XMLSchema#integer' },
  }
]};
jsonld.fromRDF(triples, { format: true, useNativeTypes: true, rdfParser: function (x) { return x; }},
               function (error, result) { console.log(JSON.stringify(result, null, '  ')); });
```

which asks to represent the single triple

``` Turtle
:MyCollection <hasCount> 16.
```

It yields:

``` JSON
[
  {
    "@id": "MyCollection",
    "hasCount": [
      {
        "@value": 16
      }
    ]
  }
]
```

while I'd expect simply

``` JSON
{
  "@id": "MyCollection",
  "hasCount": 16
}
```

**Comment by axefrog** [comment]
Hi Ruben, I've been hunting all over and can't find how you knew to format triples as you have in this issue. Is there some documentation hidden away somewhere? I even went through the API source code and couldn't find this format described anywhere. Could you point me in the right direction?

**Comment by RubenVerborgh** [comment]
Hi @axefrog, here is how I did it: https://github.com/LinkedDataFragments/Server.js/blob/v1.1.6/lib/writers/JsonLdWriter.js#L46-L51

**Comment by axefrog** [comment]
Wow, that was quick, thanks!
