### ISSUE TITLE
playground: replace tinyurl with another URL shortener

### ISSUE THREAD

**Issue by VladimirAlexiev** [digitalbazaar/jsonld.js#549]
(Don't know any better repo to report https://json-ld.org/playground/ problems. @msporny @gkellogg could you please dispatch?)

TinyURL has gone commercial:
```
Have 14 days of a TinyURL Subscription on us!
We want to treat you to a free trial of TinyURL's paid features. Just click the button below to sign up and avail of features like:
Once you’ve signed up, you have 14 whole days to take your link management and branding to the next level.
```
Please replace it with some other shortener service.

**Comment by msporny** [comment]
Transferring issue to https://github.com/json-ld/json-ld.org/issues/838
