### ISSUE TITLE
Objectify function not working for me

### ISSUE THREAD

**Issue by jessevdam** [digitalbazaar/jsonld.js#55]
I have a compacted and framed input, which I would like to load as objects using the objectify function.
However, to get it working I had to call the objectify function as followed
<pre>input = JSON.parse("sourc.json");
jsonld.objectify(input['@graph'], input['@context'], {expandContext:input['@context']},
    function(err, result) {
      //do something
  });
</pre>

and had to add the following 2 changes to the objectify function
<pre> -var top = compacted[graph][0];
 +var top = {};
 +var content = compacted[graph];
 +for(var key in content)
 +{
 +  elem = content[key]
 +  top[elem['@id']] = elem;
 +}

 -recurse(top);
 +//iterate over all objects
 +for(var elem in top)
 +{
 +  recurse(top[elem]);
 +}    
</pre>

I do not know whether I do something wrong, but I think it would be also convenient if I can just call the objectify function with only my framed and compacted input and that it automatically takes the context from the input.

**Comment by dlongley** [comment]
Objectify has been deprecated in favor of using `@link` with JSON-LD framing. See: https://github.com/json-ld/json-ld.org/issues/377.
