### ISSUE TITLE
jsonld as hashing mechanism

### ISSUE THREAD

**Issue by jeromew** [digitalbazaar/jsonld.js#66]
Hello,

I would like to start using json-ld and am very interested in the normalization procedure that could apparently help in building a deterministic hash of json objects. Since I already have objects that do not yet have a formal context, I naively tried

    ld.normalize({ "key": "value" },{format: 'application/nquads'}, function(err, n) { console.log(n); } );

but the result is empty.

then I tried

    ld.normalize({ "@context": "http://schema.org/", "key": "value" },{format: 'application/nquads'}, function(err, n) { console.log(n); } );

which gives me

    _:c14n0 <http://schema.org/key> "value" .

trying with more complex objects (with a hierarchy, arrays) seem to effectively built a unique representation of the object.

is adding `"@context": "http://schema.org/"` the correct way to go to enter the json-ld world and benefit from the normalization procedure ? should I add another context ?

My goal is to build a cache signature of an entity that depends on a json configuration ; am I right to think that json-ld is a good candidate for this job ? are there other options ?

Is the normalization spec / implementation in jsonld.js already sufficiently robust or should I expect my signatures to be modified in later upgrades of jsonld.js (this is not a problem for me I just need to know if I have to expect a full refresh of my entities after an upgrade ;-)

Thank you for your help

**Comment by dlongley** [comment]
This seems to be addressed; closing.
