### ISSUE TITLE
Can't install jsonld.js CLI on windows

### ISSUE THREAD

**Issue by viztastic** [digitalbazaar/jsonld.js#85]
Hi, I have followed the instructions provided on https://www.npmjs.com/package/jsonld under 'Using the command line tool', and when I 'npm install', I get this:

![image](https://cloud.githubusercontent.com/assets/8556736/5575646/6ba25670-9037-11e4-9747-4b8b561a9ecb.png)

Please help! @davidlehn @dlongley

**Comment by dlongley** [comment]
This may have been fixed with a new version of contextify. Can you try again?

**Comment by dlongley** [comment]
Closing this now. If it remains a problem, please reopen or file a new issue.
