### ISSUE TITLE
npm install fails with io.js

### ISSUE THREAD

**Issue by ralphtheninja** [digitalbazaar/jsonld.js#86]
Depends on

- [x] `jsdom` https://github.com/tmpvar/jsdom/issues/1005, which depends on
- [x] `contextify` https://github.com/brianmcd/contextify/issues/146

**Comment by ralphtheninja** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by kevinprotoss** [comment]
Just for information:
Almost the same error occurs on node.js 0.11.15 too.

**Comment by dlongley** [comment]
This appears to working now that contextify has been fixed.
