### ISSUE TITLE
Parse to RDF Interfaces (instead of just nquads String)

### ISSUE THREAD

**Issue by betehess** [digitalbazaar/jsonld.js#88]
Currently, the only output for `jsonld.toRDF` is a big serialized graph. This is not very practical for RDF applications.

Would it be possible to get a real datastructure instead? Something from [RDF Interfaces](http://www.w3.org/TR/rdf-interfaces/) would be the best candidate.

I would also like to know if being able to use a [ProcessorCallback](http://www.w3.org/TR/rdf-interfaces/#idl-def-ProcessorCallback) would be something you'd consider, but that'd change the main interface I believe?

**Comment by dlongley** [comment]
You can get a data structure by not passing a format. Passing a format will give you a serialized string as output. The data structure isn't well documented and doesn't conform to RDF Interfaces, but the plan is to change that in the future (make it conformant) -- we just haven't had any time. I think the output is a JavaScript object with keys that are graph names (```@default``` for the default graph) and arrays of triples for the values. Each triple has ```subject```, ```predicate```, and ```object```. And each of those has a value and a type.

We originally did have something similar to a ProcessorCallback interface but that was scraped in favor of a simpler one-off output API. We could probably add it back as a "value-add" part of jsonld.js at some point.

**Comment by betehess** [comment]
This is nice! I will experiment with no-format thing later today.

Would you me me to close this issue, and create 2 new ones re: ProcessorCallback and using RDF Interfaces?

**Comment by dlongley** [comment]
> Would you me me to close this issue, and create 2 new ones re: ProcessorCallback and using RDF Interfaces?

Sure, that would be helpful, thanks. :)
