### ISSUE TITLE
Expand treatment of sets that are elements of a map/index

### ISSUE THREAD

**Issue by hapnermw** [digitalbazaar/jsonld.js#90]
The JSON LD spec documents that map elements can be arrays or set objects; however, nowhere in the spec that I can find does it document how these map element are expanded.
For example, if the input to expand is:
```
{ '@context': { map: { '@id': '_:my_map', '@container': '@index' } },
  map: 
   { foo: [ 'foo1-element', 'foo2-element' ],
     bar: { '@set': [ 'bar1-element', 'bar2-element' ] },
     baz: { '@list': [ 'baz-element' ] },
     x: { '@id': '_:2' },
     y: { '@value': false },
     z: 6 },
  '@id': '_:my_id',
  '@type': '_:my_type' }
```
The output is:
```
[ { '@id': '_:my_id',
    '@type': [ '_:my_type' ],
    '_:my_map': 
     [ { '@value': 'bar1-element', '@index': 'bar' },
       { '@value': 'bar2-element', '@index': 'bar' },
       { '@list': [ { '@value': 'baz-element' } ], '@index': 'baz' },
       { '@value': 'foo1-element', '@index': 'foo' },
       { '@value': 'foo2-element', '@index': 'foo' },
       { '@id': '_:2', '@index': 'x' },
       { '@value': false, '@index': 'y' },
       { '@value': 6, '@index': 'z' } ] } ]
```

The array and set elements of the map are shredded into individual value objects with each given the index of their map entry. This Expand set shredding is likely to surprise most users.
In general, JSON LD has an issue of non-orthogonal conversion of set elements between the two indexed representations. 
If a set object with an @index property is an element of an indexed set, Expand deletes this entry which is also likely to be surprising.
An alternative would have been to require indexed set elements to always use the set object form that Expand would retain; however, it is likely too late for this now.
At this point, it would likely be best to warn users to avoid this case (both in the JSON LD spec and the Expand docs) and wrap all index set elements in a node so they won’t be shredded/deleted by Expand.

**Comment by dlongley** [comment]
> The array and set elements of the map are shredded into individual value objects with each given the index of their map entry. This Expand set shredding is likely to surprise most users.

`@index` keys are not part of the data (as in, they don't fit into the RDF data model). They are sugar only, to allow for data structuring via context. Expanded form is generally for algorithmic processing only; typically used to transition from one context to another or to/from RDF. Most applications should use compacted form with a context specific to the particular application.

> however, nowhere in the spec that I can find does it document how these map element are expanded.

Have you read the [API spec](http://www.w3.org/TR/json-ld-api/) as well or just the main [syntax spec](http://www.w3.org/TR/json-ld/)?

Here's where `@index` is covered by the syntax spec: http://www.w3.org/TR/json-ld/#data-indexing

And the details of the expansion algorithm, including how `@index` is dealt with, can be found here in the API spec: http://www.w3.org/TR/json-ld-api/#expansion-algorithms

**Comment by dlongley** [comment]
Closing; reopen if unresolved.
