### ISSUE TITLE
fromRDF throws exception instead of setting err

### ISSUE THREAD

**Issue by alf** [digitalbazaar/jsonld.js#91]
_parseNquads is synchronous and throws on invalid input. This is not picked up when calling parseRdf.

**Comment by dlongley** [comment]
Thanks, @alf. This should be fixed but needs a test case added; I'm leaving it open until we have time to add one.

**Comment by alf** [comment]
Thank you, that was very quickly delivered and released. I'm impressed and happy. :)

**Comment by dlongley** [comment]
Sure :)

**Comment by dlongley** [comment]
Closing issue as it is 5 years old and the implementation has moved on.
