### ISSUE TITLE
browserify --standalone (to expose an UMD interface) fails

### ISSUE THREAD

**Issue by StatelessCat** [digitalbazaar/jsonld.js#92]
Hey,
I got

``` js
module.exports = jsonldjs;
                 ^
ReferenceError: jsonldjs is not defined
```

After browserify a [trivial lib](https://github.com/StatelessCat/umd-lib) that is using jsonld.js.

Steps to reproduce:

```
npm install jsonld
```

Use it with a code [like this](https://github.com/StatelessCat/umd-lib/blob/master/node/nodeTest.js)

``` sh
browserify src/mylib.js --standalone mylib > src/bundle.js
```

``` js
node node/nodeTest.js
```

```
module.exports = jsonldjs;
                 ^
ReferenceError: jsonldjs is not defined
```

Maybe it's related to [this](https://github.com/digitalbazaar/jsonld.js/commit/e479329c1a15331fcbfe32d98c39adab27250200) ? 

Maybe there is another issue with jsonld.promises after browserify --standalone, but i think it's related to the previous failure.

Thank you for your help, or any advise if i forgot a step.

**Comment by dlongley** [comment]
Thanks @StatelessCat. This should be fixed now. We should add a test case to prevent future regressions, so I'm going to leave it open until we can get to that.

**Comment by StatelessCat** [comment]
Thanks @dlongley, It's working well right now.

**Comment by dlongley** [comment]
Sure :)

**Comment by dlongley** [comment]
How we package has changed in the last 5 years, closing.
