### ISSUE TITLE
Bug with data indexing when flattening/converting to RDF

### ISSUE THREAD

**Issue by lanthaler** [digitalbazaar/jsonld.js#95]
A user reported this on Stackoverflow: http://stackoverflow.com/questions/28836484/is-this-a-correct-use-of-json-ld-index-maps

Neither Gregg's distiller nor [my playground](http://www.markus-lanthaler.com/jsonld/playground/?json-ld=%7B%0A%20%20%22%40context%22%20%3A%20%7B%0A%20%20%20%20%22%40base%22%20%3A%20%22http%3A%2F%2Fwww.example.com%2Fdata%2F%22%2C%0A%20%20%20%20%22%40vocab%22%20%3A%20%22http%3A%2F%2Fwww.example.com%2Fvocab%23%22%2C%0A%20%20%20%20%22knows%22%20%3A%20%7B%0A%20%20%20%20%20%20%22%40container%22%20%3A%20%22%40index%22%2C%0A%20%20%20%20%20%20%22%40id%22%20%3A%20%22schema%3Aknows%22%2C%0A%20%20%20%20%20%20%22%40type%22%20%3A%20%22%40id%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22name%22%20%3A%20%22schema%3Aname%22%2C%0A%20%20%20%20%22people%22%20%3A%20%7B%0A%20%20%20%20%20%20%22%40container%22%20%3A%20%22%40index%22%2C%0A%20%20%20%20%20%20%22%40id%22%20%3A%20%22people%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22schema%22%20%3A%20%22http%3A%2F%2Fschema.org%2F%22%0A%20%20%7D%2C%0A%20%20%22%40id%22%20%3A%20%22http%3A%2F%2Fwww.example.com%22%2C%0A%20%20%22people%22%20%3A%20%7B%0A%20%20%20%20%22person1%22%20%3A%20%7B%0A%20%20%20%20%20%20%22%40id%22%20%3A%20%22people%2Fperson1%22%2C%0A%20%20%20%20%20%20%22knows%22%20%3A%20%7B%0A%20%20%20%20%20%20%20%20%22person2%22%20%3A%20%22people%2Fperson2%22%2C%0A%20%20%20%20%20%20%20%20%22person3%22%20%3A%20%22people%2Fperson3%22%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22name%22%20%3A%20%22Person%201%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22person2%22%20%3A%20%7B%0A%20%20%20%20%20%20%22%40id%22%20%3A%20%22people%2Fperson2%22%2C%0A%20%20%20%20%20%20%22name%22%20%3A%20%22Person%202%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22person3%22%20%3A%20%7B%0A%20%20%20%20%20%20%22%40id%22%20%3A%20%22people%2Fperson3%22%2C%0A%20%20%20%20%20%20%22name%22%20%3A%20%22Person%203%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22person4%22%20%3A%20%7B%0A%20%20%20%20%20%20%22%40id%22%20%3A%20%22people%2Fperson4%22%2C%0A%20%20%20%20%20%20%22name%22%20%3A%20%22Person%204%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&frame=%7B%7D&context=%7B%7D&startTab=tab-to_rdf) have an issue with this. There are no conflicting indexes AFAICS, the index for `http://www.example.com/data/people/person2` is in all cases `person2`

**Comment by davidlehn** [comment]
Should probably file a bug on the test suite to catch this issue too.

**Comment by dlongley** [comment]
Closing as likely fixed long ago, please reopen if needed.
