### ISSUE TITLE
Schema help

### ISSUE THREAD

**Issue by cadorn** [digitalbazaar/jsonld.js#96]
I am looking at integrating json-ld into my system. Need some assistance to get started.

Given:
````
{
	"@context": {
		"config": {
			"@context": {
			}
		}
	},
	"config": {
		"hostname1.com/0": {
			"programs": {
				"demo": "./.../program.json"
			}
		},
		"hostname2.com/0": {
			"programs": {
				"demo": "./.../program.json"
			}
		}
	}
}
````

How would I write the contexts to express this in both ways:

  1. Be able to use only declared values for `config[*]` i.e. `hostname1.com/0` must be declared in context.
  2. Be able to use any declared value for  `config[*]` as a variable in the context to lookup the context for the JSON underneath.

If one and/or two is not possible I need to look at writing a converter that takes the raw inout JSON and formats it to something JSON-LD compatible. What would the best compatible structure look like?

Is there one tutorial or video you would recommend that explains the syntax best to get me started? I find the playground on the site a bit too inconsistent and advanced. Its good so see data converted but not good to see how to code schemas.

**Comment by dlongley** [comment]
Hey @cadorn,

This question would probably be better asked at https://github.com/json-ld.org or on the JSON-LD mailing list: public-linked-json@w3.org.

Here are some links to a short video series about JSON-LD:

[What is Linked Data?](http://www.youtube.com/watch?v=4x_xzT5eF5Q)

A short non-technical introduction to Linked Data, Google's Knowledge
Graph, and Facebook's Open Graph Protocol.

-------------------
[What is JSON-LD?](http://www.youtube.com/watch?v=vioCbTo3C-4)

A short introduction to JSON-LD for Web developers, designers, and
hobbyists. It covers how to express basic Linked Data in JSON.

-------------------
[JSON-LD: Compaction and Expansion](http://www.youtube.com/watch?v=Tm3fD89dqRE)

An overview of JSON-LD's compaction and expansion features and how you
can use them to merge data from multiple sources.

-------------------
[JSON-LD: Core Markup](http://www.youtube.com/watch?v=UmvWk_TQ30A)

An overview of some of the core markup features of JSON-LD including
types, aliasing, nesting, and internationalization support.

**Comment by cadorn** [comment]
Got what I need for now. Thanks. Need to build a converter to and from json-ld and then it should work great.

**Comment by dlongley** [comment]
Sure :)
