### ISSUE TITLE
Infinite recursion when data contains cyclic dependencies

### ISSUE THREAD

**Issue by znerol** [digitalbazaar/jsonld.js#97]
Given the following data-structure containing cyclic dependencies:

    var jsonld = require('jsonld');

    var a = {
      "@context": {"@vocab": "http://schema.org"},
      "@id": "http://example.com/a",
      hasPart: []
    }
    var b = {
      "@context": {"@vocab": "http://schema.org"},
      "@id": "http://example.com/b",
      isPartOf: []
    }

    a.hasPart.push(b);
    b.isPartOf.push(a);

    jsonld.flatten(a);

I get the following `RangeError`:

    /tmp/node_modules/jsonld/js/jsonld.js:5836
      return (Object.prototype.toString.call(v) === '[object Object]');
                                        ^
    RangeError: Maximum call stack size exceeded

Instead I'd expect the following output:

    {
      "@context": {
        "@vocab": "http://schema.org/"
      },
      "@graph": [
        {
          "@id": "http://example.com/a",
          "hasPart": {
            "@id": "http://example.com/b"
          }
        },
        {
          "@id": "http://example.com/b",
          "isPartOf": {
            "@id": "http://example.com/a"
          }
        }
      ]
    }

I see the same behavior in `pyld`, so I'm not sure whether this is an implementation problem or an issue with the API spec.

**Comment by znerol** [comment]
This also happens when attempting to `flatten()` a data structure which has been `link()`ed before:

    var jsonld = require('jsonld');

    var ctx = {"@vocab": "http://schema.org"}
    var input = {
      "@context": ctx,
      "@graph": [
        {
          "@id": "http://example.com/a",
          "hasPart": [{"@id": "http://example.com/b"}]
        },
        {
          "@id": "http://example.com/b",
          "isPartOf": [{"@id": "http://example.com/a"}]
        }
      ]
    }

    jsonld.link(input, ctx, {}, function(err, linked) {
      jsonld.flatten(linked, ctx);
    });

**Comment by dlongley** [comment]
@znerol, there's an expectation that the input to any JSON-LD algorithm is a JSON object, not a JavaScript object. JSON objects cannot have circular references. In short, don't pass anything generated by `link` back through any JSON-LD algorithm.

**Comment by znerol** [comment]
Are there any recommendations on how to *unlink* a linked structure?

**Comment by dlongley** [comment]
@znerol, unfortunately, we don't have any API calls to do it in `jsonld.js` ... you can always write a function that will cycle through an object and track when it hits a cyclical reference and instead replace it with a clone the data.

There's probably code you can adapt to do that at stackoverflow somewhere. For example: [this may help](http://stackoverflow.com/questions/15312529/resolve-circular-references-from-json-object).

And perhaps this npm package could help?: [circular-json](https://www.npmjs.com/package/circular-json)
