### ISSUE TITLE
Make RDFa parser an optional addon

### ISSUE THREAD

**Issue by BigBlueHat** [digitalbazaar/jsonld.js#98]
DOM parsing is a pretty hefty requirement and this library is still quite useful without that overhead.

Thanks!

**Comment by dlongley** [comment]
+1 to splitting RDFa support out into an optional extension.

Related to #41.

**Comment by msporny** [comment]
+1 to RDFa as an optional extension.

**Comment by elf-pavlik** [comment]
:+1:

**Comment by davidlehn** [comment]
The "request" extension and dependencies were moved to https://github.com/digitalbazaar/jsonld-request.  While RDFa is not yet optional in jsonld-request, it is no longer required for the core jsonld.js library.

**Comment by dlongley** [comment]
If RDFa is to be made optional in jsonld-request, an issue for that should be opened over there. This issue has been resolved with version 0.4, so I'm closing it.

**Comment by elf-pavlik** [comment]
awesome :dancers:  great work guys!
